// GENERATED by tests/cpp/generate_pins.cpp. Do not hand-edit.
//
// Regenerate only when a numeric change has been reviewed and accepted:
//   cmake --build build-debug --target maptitude_pin_generator
//   ./build-debug/tests/cpp/maptitude_pin_generator > tests/cpp/pin_values.h
#ifndef MAPTITUDE_TEST_PIN_VALUES_H
#define MAPTITUDE_TEST_PIN_VALUES_H

namespace MaptitudePins {

constexpr double RSCC_CARBON_BINNED = 0.9105036927608251;
constexpr double RSCC_CARBON_FIXED = 0.85714050393647834;
constexpr double RSCC_CARBON_SCALED = 0.94997171262350288;
constexpr double RSCC_OXYGEN_OFFSET = 0.91733007239850817;
constexpr double RSR_CARBON_BINNED = 0.10158040898505934;
constexpr double RSR_CARBON_ADAPTIVE = 0.065528568920786359;
constexpr double QSCORE_CARBON_DEFAULT = 0.96296527998254844;
constexpr double QSCORE_CARBON_SIGMA08 = 0.9943922001151142;
constexpr double EDIAM_CARBON_DEFAULT = 0.99872898373691865;
constexpr double COVERAGE_CARBON_DEFAULT = 1;
constexpr double COVERAGE_CARBON_SIGMA24 = 0;

}  // namespace MaptitudePins

#endif  // MAPTITUDE_TEST_PIN_VALUES_H
