// GENERATED by tests/cpp/generate_pins.cpp. Do not hand-edit.
//
// Regenerate only when a numeric change has been reviewed and accepted:
//   cmake --build build-debug --target maptitude_pin_generator
//   ./build-debug/tests/cpp/maptitude_pin_generator > tests/cpp/pin_values.h
#ifndef MAPTITUDE_TEST_PIN_VALUES_H
#define MAPTITUDE_TEST_PIN_VALUES_H

namespace MaptitudePins {

constexpr double RSCC_CARBON_BINNED = 0.9105036927608251;
constexpr double RSCC_CARBON_FIXED = 0.85714050393647834;
constexpr double RSCC_CARBON_SCALED = 0.94997171262350288;
constexpr double RSCC_OXYGEN_OFFSET = 0.91733007239850817;
constexpr double RSR_CARBON_BINNED = 0.10158040898505934;
constexpr double RSR_CARBON_ADAPTIVE = 0.065528568920786359;
constexpr double RSR_CARBON_DEFAULT = 0.065528568920786359;
constexpr double RSR_CARBON_FIXED = 0.077046454424099547;
constexpr double RSR_CARBON_SCALED = 0.13351152007626726;
constexpr double QSCORE_CARBON_DEFAULT = 0.96296527987682856;
constexpr double QSCORE_CARBON_SIGMA08 = 0.99439220042494902;
constexpr double EDIAM_CARBON_DEFAULT = 0.99872898373691865;
constexpr double COVERAGE_CARBON_DEFAULT = 1;
constexpr double COVERAGE_CARBON_SIGMA24 = 0;
constexpr double COVERAGE_TWO_ATOM_SPLIT = 0.5;
constexpr double FC_ORTHORHOMBIC_SUM = 40573.911944538355;
constexpr double FC_ORTHORHOMBIC_SUM_SQ = 107345.02203126957;
constexpr double FC_ORTHORHOMBIC_MIN = 0.20206983387470245;
constexpr double FC_ORTHORHOMBIC_MAX = 2.6758720874786377;
constexpr double FC_ORTHORHOMBIC_INDEX_MOMENT = -6449860.6243932191;
constexpr double FC_ORTHORHOMBIC_SHELLS4_SUM = 13937.487342774868;
constexpr double FC_ORTHORHOMBIC_SHELLS4_SUM_SQ = 12433.449584055335;
constexpr double FC_ORTHORHOMBIC_SHELLS4_MIN = 0.82111889123916626;
constexpr double FC_ORTHORHOMBIC_SHELLS4_MAX = 1;
constexpr double FC_ORTHORHOMBIC_SHELLS4_INDEX_MOMENT = -115006.82435095034;
constexpr double FC_ORTHORHOMBIC_ASYM_SUM = 39687.334927231073;
constexpr double FC_ORTHORHOMBIC_ASYM_SUM_SQ = 103884.34889120319;
constexpr double FC_ORTHORHOMBIC_ASYM_MIN = 0.20206983387470245;
constexpr double FC_ORTHORHOMBIC_ASYM_MAX = 2.6758720874786377;
constexpr double FC_ORTHORHOMBIC_ASYM_INDEX_MOMENT = 2334956.3627410433;
constexpr double GRIDOPS_SCALE_SUM = 0;
constexpr double GRIDOPS_SCALE_SUM_SQ = 27613608.75;
constexpr double GRIDOPS_SCALE_MIN = -333;
constexpr double GRIDOPS_SCALE_MAX = 333;
constexpr double GRIDOPS_SCALE_INDEX_MOMENT = 29856195;
constexpr double GRIDOPS_ADD_SUM = 7290;
constexpr double GRIDOPS_ADD_SUM_SQ = 12345615;
constexpr double GRIDOPS_ADD_MIN = -212;
constexpr double GRIDOPS_ADD_MAX = 232;
constexpr double GRIDOPS_ADD_INDEX_MOMENT = 19904130;
constexpr double GRIDOPS_SUBTRACT_SUM = -7290;
constexpr double GRIDOPS_SUBTRACT_SUM_SQ = 12345615;
constexpr double GRIDOPS_SUBTRACT_MIN = -232;
constexpr double GRIDOPS_SUBTRACT_MAX = 212;
constexpr double GRIDOPS_SUBTRACT_INDEX_MOMENT = 19904130;
constexpr double GRIDOPS_MIN_SUM = -24755;
constexpr double GRIDOPS_MIN_SUM_SQ = 6914492.5;
constexpr double GRIDOPS_MIN_MIN = -222;
constexpr double GRIDOPS_MIN_MAX = 50;
constexpr double GRIDOPS_MIN_INDEX_MOMENT = 13220280;
constexpr double GRIDOPS_MAX_SUM = 24755;
constexpr double GRIDOPS_MAX_SUM_SQ = 6914492.5;
constexpr double GRIDOPS_MAX_MIN = -50;
constexpr double GRIDOPS_MAX_MAX = 222;
constexpr double GRIDOPS_MAX_INDEX_MOMENT = 13220280;
constexpr double GRIDOPS_DIFF_TO_CALC_SUM = -4374;
constexpr double GRIDOPS_DIFF_TO_CALC_SUM_SQ = 12298959;
constexpr double GRIDOPS_DIFF_TO_CALC_MIN = -228;
constexpr double GRIDOPS_DIFF_TO_CALC_MAX = 216;
constexpr double GRIDOPS_DIFF_TO_CALC_INDEX_MOMENT = 19904130;

}  // namespace MaptitudePins

#endif  // MAPTITUDE_TEST_PIN_VALUES_H
