# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.4.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if getattr(globals().get("__spec__"), "parent", None) or __package__ or "." in __name__:
    from . import _maptitude
else:
    import _maptitude

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _maptitude.delete_SwigPyIterator

    def value(self):
        return _maptitude.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _maptitude.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _maptitude.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _maptitude.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _maptitude.SwigPyIterator_equal(self, x)

    def copy(self):
        return _maptitude.SwigPyIterator_copy(self)

    def next(self):
        return _maptitude.SwigPyIterator_next(self)

    def __next__(self):
        return _maptitude.SwigPyIterator___next__(self)

    def previous(self):
        return _maptitude.SwigPyIterator_previous(self)

    def advance(self, n):
        return _maptitude.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _maptitude.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _maptitude.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _maptitude.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _maptitude.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _maptitude.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _maptitude.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _maptitude:
_maptitude.SwigPyIterator_swigregister(SwigPyIterator)
class DoubleVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _maptitude.DoubleVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _maptitude.DoubleVector___nonzero__(self)

    def __bool__(self):
        return _maptitude.DoubleVector___bool__(self)

    def __len__(self):
        return _maptitude.DoubleVector___len__(self)

    def __getslice__(self, i, j):
        return _maptitude.DoubleVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _maptitude.DoubleVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _maptitude.DoubleVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _maptitude.DoubleVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _maptitude.DoubleVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _maptitude.DoubleVector___setitem__(self, *args)

    def pop(self):
        return _maptitude.DoubleVector_pop(self)

    def append(self, x):
        return _maptitude.DoubleVector_append(self, x)

    def empty(self):
        return _maptitude.DoubleVector_empty(self)

    def size(self):
        return _maptitude.DoubleVector_size(self)

    def swap(self, v):
        return _maptitude.DoubleVector_swap(self, v)

    def begin(self):
        return _maptitude.DoubleVector_begin(self)

    def end(self):
        return _maptitude.DoubleVector_end(self)

    def rbegin(self):
        return _maptitude.DoubleVector_rbegin(self)

    def rend(self):
        return _maptitude.DoubleVector_rend(self)

    def clear(self):
        return _maptitude.DoubleVector_clear(self)

    def get_allocator(self):
        return _maptitude.DoubleVector_get_allocator(self)

    def pop_back(self):
        return _maptitude.DoubleVector_pop_back(self)

    def erase(self, *args):
        return _maptitude.DoubleVector_erase(self, *args)

    def __init__(self, *args):
        _maptitude.DoubleVector_swiginit(self, _maptitude.new_DoubleVector(*args))

    def push_back(self, x):
        return _maptitude.DoubleVector_push_back(self, x)

    def front(self):
        return _maptitude.DoubleVector_front(self)

    def back(self):
        return _maptitude.DoubleVector_back(self)

    def assign(self, n, x):
        return _maptitude.DoubleVector_assign(self, n, x)

    def resize(self, *args):
        return _maptitude.DoubleVector_resize(self, *args)

    def insert(self, *args):
        return _maptitude.DoubleVector_insert(self, *args)

    def reserve(self, n):
        return _maptitude.DoubleVector_reserve(self, n)

    def capacity(self):
        return _maptitude.DoubleVector_capacity(self)
    __swig_destroy__ = _maptitude.delete_DoubleVector

# Register DoubleVector in _maptitude:
_maptitude.DoubleVector_swigregister(DoubleVector)
class UnsignedIntVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _maptitude.UnsignedIntVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _maptitude.UnsignedIntVector___nonzero__(self)

    def __bool__(self):
        return _maptitude.UnsignedIntVector___bool__(self)

    def __len__(self):
        return _maptitude.UnsignedIntVector___len__(self)

    def __getslice__(self, i, j):
        return _maptitude.UnsignedIntVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _maptitude.UnsignedIntVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _maptitude.UnsignedIntVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _maptitude.UnsignedIntVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _maptitude.UnsignedIntVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _maptitude.UnsignedIntVector___setitem__(self, *args)

    def pop(self):
        return _maptitude.UnsignedIntVector_pop(self)

    def append(self, x):
        return _maptitude.UnsignedIntVector_append(self, x)

    def empty(self):
        return _maptitude.UnsignedIntVector_empty(self)

    def size(self):
        return _maptitude.UnsignedIntVector_size(self)

    def swap(self, v):
        return _maptitude.UnsignedIntVector_swap(self, v)

    def begin(self):
        return _maptitude.UnsignedIntVector_begin(self)

    def end(self):
        return _maptitude.UnsignedIntVector_end(self)

    def rbegin(self):
        return _maptitude.UnsignedIntVector_rbegin(self)

    def rend(self):
        return _maptitude.UnsignedIntVector_rend(self)

    def clear(self):
        return _maptitude.UnsignedIntVector_clear(self)

    def get_allocator(self):
        return _maptitude.UnsignedIntVector_get_allocator(self)

    def pop_back(self):
        return _maptitude.UnsignedIntVector_pop_back(self)

    def erase(self, *args):
        return _maptitude.UnsignedIntVector_erase(self, *args)

    def __init__(self, *args):
        _maptitude.UnsignedIntVector_swiginit(self, _maptitude.new_UnsignedIntVector(*args))

    def push_back(self, x):
        return _maptitude.UnsignedIntVector_push_back(self, x)

    def front(self):
        return _maptitude.UnsignedIntVector_front(self)

    def back(self):
        return _maptitude.UnsignedIntVector_back(self)

    def assign(self, n, x):
        return _maptitude.UnsignedIntVector_assign(self, n, x)

    def resize(self, *args):
        return _maptitude.UnsignedIntVector_resize(self, *args)

    def insert(self, *args):
        return _maptitude.UnsignedIntVector_insert(self, *args)

    def reserve(self, n):
        return _maptitude.UnsignedIntVector_reserve(self, n)

    def capacity(self):
        return _maptitude.UnsignedIntVector_capacity(self)
    __swig_destroy__ = _maptitude.delete_UnsignedIntVector

# Register UnsignedIntVector in _maptitude:
_maptitude.UnsignedIntVector_swigregister(UnsignedIntVector)
class SymOpVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _maptitude.SymOpVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _maptitude.SymOpVector___nonzero__(self)

    def __bool__(self):
        return _maptitude.SymOpVector___bool__(self)

    def __len__(self):
        return _maptitude.SymOpVector___len__(self)

    def __getslice__(self, i, j):
        return _maptitude.SymOpVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _maptitude.SymOpVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _maptitude.SymOpVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _maptitude.SymOpVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _maptitude.SymOpVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _maptitude.SymOpVector___setitem__(self, *args)

    def pop(self):
        return _maptitude.SymOpVector_pop(self)

    def append(self, x):
        return _maptitude.SymOpVector_append(self, x)

    def empty(self):
        return _maptitude.SymOpVector_empty(self)

    def size(self):
        return _maptitude.SymOpVector_size(self)

    def swap(self, v):
        return _maptitude.SymOpVector_swap(self, v)

    def begin(self):
        return _maptitude.SymOpVector_begin(self)

    def end(self):
        return _maptitude.SymOpVector_end(self)

    def rbegin(self):
        return _maptitude.SymOpVector_rbegin(self)

    def rend(self):
        return _maptitude.SymOpVector_rend(self)

    def clear(self):
        return _maptitude.SymOpVector_clear(self)

    def get_allocator(self):
        return _maptitude.SymOpVector_get_allocator(self)

    def pop_back(self):
        return _maptitude.SymOpVector_pop_back(self)

    def erase(self, *args):
        return _maptitude.SymOpVector_erase(self, *args)

    def __init__(self, *args):
        _maptitude.SymOpVector_swiginit(self, _maptitude.new_SymOpVector(*args))

    def push_back(self, x):
        return _maptitude.SymOpVector_push_back(self, x)

    def front(self):
        return _maptitude.SymOpVector_front(self)

    def back(self):
        return _maptitude.SymOpVector_back(self)

    def assign(self, n, x):
        return _maptitude.SymOpVector_assign(self, n, x)

    def resize(self, *args):
        return _maptitude.SymOpVector_resize(self, *args)

    def insert(self, *args):
        return _maptitude.SymOpVector_insert(self, *args)

    def reserve(self, n):
        return _maptitude.SymOpVector_reserve(self, n)

    def capacity(self):
        return _maptitude.SymOpVector_capacity(self)
    __swig_destroy__ = _maptitude.delete_SymOpVector

# Register SymOpVector in _maptitude:
_maptitude.SymOpVector_swigregister(SymOpVector)
class ResidueDoubleMap(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _maptitude.ResidueDoubleMap_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _maptitude.ResidueDoubleMap___nonzero__(self)

    def __bool__(self):
        return _maptitude.ResidueDoubleMap___bool__(self)

    def __len__(self):
        return _maptitude.ResidueDoubleMap___len__(self)
    def __iter__(self):
        return self.key_iterator()
    def iterkeys(self):
        return self.key_iterator()
    def itervalues(self):
        return self.value_iterator()
    def iteritems(self):
        return self.iterator()

    def __getitem__(self, key):
        return _maptitude.ResidueDoubleMap___getitem__(self, key)

    def __delitem__(self, key):
        return _maptitude.ResidueDoubleMap___delitem__(self, key)

    def has_key(self, key):
        return _maptitude.ResidueDoubleMap_has_key(self, key)

    def keys(self):
        return _maptitude.ResidueDoubleMap_keys(self)

    def values(self):
        return _maptitude.ResidueDoubleMap_values(self)

    def items(self):
        return _maptitude.ResidueDoubleMap_items(self)

    def __contains__(self, key):
        return _maptitude.ResidueDoubleMap___contains__(self, key)

    def key_iterator(self):
        return _maptitude.ResidueDoubleMap_key_iterator(self)

    def value_iterator(self):
        return _maptitude.ResidueDoubleMap_value_iterator(self)

    def __setitem__(self, *args):
        return _maptitude.ResidueDoubleMap___setitem__(self, *args)

    def asdict(self):
        return _maptitude.ResidueDoubleMap_asdict(self)

    def __init__(self, *args):
        _maptitude.ResidueDoubleMap_swiginit(self, _maptitude.new_ResidueDoubleMap(*args))

    def empty(self):
        return _maptitude.ResidueDoubleMap_empty(self)

    def size(self):
        return _maptitude.ResidueDoubleMap_size(self)

    def swap(self, v):
        return _maptitude.ResidueDoubleMap_swap(self, v)

    def begin(self):
        return _maptitude.ResidueDoubleMap_begin(self)

    def end(self):
        return _maptitude.ResidueDoubleMap_end(self)

    def rbegin(self):
        return _maptitude.ResidueDoubleMap_rbegin(self)

    def rend(self):
        return _maptitude.ResidueDoubleMap_rend(self)

    def clear(self):
        return _maptitude.ResidueDoubleMap_clear(self)

    def get_allocator(self):
        return _maptitude.ResidueDoubleMap_get_allocator(self)

    def count(self, x):
        return _maptitude.ResidueDoubleMap_count(self, x)

    def erase(self, *args):
        return _maptitude.ResidueDoubleMap_erase(self, *args)

    def find(self, x):
        return _maptitude.ResidueDoubleMap_find(self, x)

    def lower_bound(self, x):
        return _maptitude.ResidueDoubleMap_lower_bound(self, x)

    def upper_bound(self, x):
        return _maptitude.ResidueDoubleMap_upper_bound(self, x)
    __swig_destroy__ = _maptitude.delete_ResidueDoubleMap

# Register ResidueDoubleMap in _maptitude:
_maptitude.ResidueDoubleMap_swigregister(ResidueDoubleMap)
class UIntDoubleMap(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _maptitude.UIntDoubleMap_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _maptitude.UIntDoubleMap___nonzero__(self)

    def __bool__(self):
        return _maptitude.UIntDoubleMap___bool__(self)

    def __len__(self):
        return _maptitude.UIntDoubleMap___len__(self)
    def __iter__(self):
        return self.key_iterator()
    def iterkeys(self):
        return self.key_iterator()
    def itervalues(self):
        return self.value_iterator()
    def iteritems(self):
        return self.iterator()

    def __getitem__(self, key):
        return _maptitude.UIntDoubleMap___getitem__(self, key)

    def __delitem__(self, key):
        return _maptitude.UIntDoubleMap___delitem__(self, key)

    def has_key(self, key):
        return _maptitude.UIntDoubleMap_has_key(self, key)

    def keys(self):
        return _maptitude.UIntDoubleMap_keys(self)

    def values(self):
        return _maptitude.UIntDoubleMap_values(self)

    def items(self):
        return _maptitude.UIntDoubleMap_items(self)

    def __contains__(self, key):
        return _maptitude.UIntDoubleMap___contains__(self, key)

    def key_iterator(self):
        return _maptitude.UIntDoubleMap_key_iterator(self)

    def value_iterator(self):
        return _maptitude.UIntDoubleMap_value_iterator(self)

    def __setitem__(self, *args):
        return _maptitude.UIntDoubleMap___setitem__(self, *args)

    def asdict(self):
        return _maptitude.UIntDoubleMap_asdict(self)

    def __init__(self, *args):
        _maptitude.UIntDoubleMap_swiginit(self, _maptitude.new_UIntDoubleMap(*args))

    def empty(self):
        return _maptitude.UIntDoubleMap_empty(self)

    def size(self):
        return _maptitude.UIntDoubleMap_size(self)

    def swap(self, v):
        return _maptitude.UIntDoubleMap_swap(self, v)

    def begin(self):
        return _maptitude.UIntDoubleMap_begin(self)

    def end(self):
        return _maptitude.UIntDoubleMap_end(self)

    def rbegin(self):
        return _maptitude.UIntDoubleMap_rbegin(self)

    def rend(self):
        return _maptitude.UIntDoubleMap_rend(self)

    def clear(self):
        return _maptitude.UIntDoubleMap_clear(self)

    def get_allocator(self):
        return _maptitude.UIntDoubleMap_get_allocator(self)

    def count(self, x):
        return _maptitude.UIntDoubleMap_count(self, x)

    def erase(self, *args):
        return _maptitude.UIntDoubleMap_erase(self, *args)

    def find(self, x):
        return _maptitude.UIntDoubleMap_find(self, x)

    def lower_bound(self, x):
        return _maptitude.UIntDoubleMap_lower_bound(self, x)

    def upper_bound(self, x):
        return _maptitude.UIntDoubleMap_upper_bound(self, x)
    __swig_destroy__ = _maptitude.delete_UIntDoubleMap

# Register UIntDoubleMap in _maptitude:
_maptitude.UIntDoubleMap_swigregister(UIntDoubleMap)
class Double3Array(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _maptitude.Double3Array_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _maptitude.Double3Array___nonzero__(self)

    def __bool__(self):
        return _maptitude.Double3Array___bool__(self)

    def __len__(self):
        return _maptitude.Double3Array___len__(self)

    def __getslice__(self, i, j):
        return _maptitude.Double3Array___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _maptitude.Double3Array___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _maptitude.Double3Array___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _maptitude.Double3Array___delitem__(self, *args)

    def __getitem__(self, *args):
        return _maptitude.Double3Array___getitem__(self, *args)

    def __setitem__(self, *args):
        return _maptitude.Double3Array___setitem__(self, *args)

    def __init__(self, *args):
        _maptitude.Double3Array_swiginit(self, _maptitude.new_Double3Array(*args))

    def empty(self):
        return _maptitude.Double3Array_empty(self)

    def size(self):
        return _maptitude.Double3Array_size(self)

    def swap(self, v):
        return _maptitude.Double3Array_swap(self, v)

    def begin(self):
        return _maptitude.Double3Array_begin(self)

    def end(self):
        return _maptitude.Double3Array_end(self)

    def rbegin(self):
        return _maptitude.Double3Array_rbegin(self)

    def rend(self):
        return _maptitude.Double3Array_rend(self)

    def front(self):
        return _maptitude.Double3Array_front(self)

    def back(self):
        return _maptitude.Double3Array_back(self)

    def fill(self, u):
        return _maptitude.Double3Array_fill(self, u)
    __swig_destroy__ = _maptitude.delete_Double3Array

# Register Double3Array in _maptitude:
_maptitude.Double3Array_swigregister(Double3Array)
class Double9Array(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _maptitude.Double9Array_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _maptitude.Double9Array___nonzero__(self)

    def __bool__(self):
        return _maptitude.Double9Array___bool__(self)

    def __len__(self):
        return _maptitude.Double9Array___len__(self)

    def __getslice__(self, i, j):
        return _maptitude.Double9Array___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _maptitude.Double9Array___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _maptitude.Double9Array___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _maptitude.Double9Array___delitem__(self, *args)

    def __getitem__(self, *args):
        return _maptitude.Double9Array___getitem__(self, *args)

    def __setitem__(self, *args):
        return _maptitude.Double9Array___setitem__(self, *args)

    def __init__(self, *args):
        _maptitude.Double9Array_swiginit(self, _maptitude.new_Double9Array(*args))

    def empty(self):
        return _maptitude.Double9Array_empty(self)

    def size(self):
        return _maptitude.Double9Array_size(self)

    def swap(self, v):
        return _maptitude.Double9Array_swap(self, v)

    def begin(self):
        return _maptitude.Double9Array_begin(self)

    def end(self):
        return _maptitude.Double9Array_end(self)

    def rbegin(self):
        return _maptitude.Double9Array_rbegin(self)

    def rend(self):
        return _maptitude.Double9Array_rend(self)

    def front(self):
        return _maptitude.Double9Array_front(self)

    def back(self):
        return _maptitude.Double9Array_back(self)

    def fill(self, u):
        return _maptitude.Double9Array_fill(self, u)
    __swig_destroy__ = _maptitude.delete_Double9Array

# Register Double9Array in _maptitude:
_maptitude.Double9Array_swigregister(Double9Array)
MAPTITUDE_VERSION_MAJOR = _maptitude.MAPTITUDE_VERSION_MAJOR
MAPTITUDE_VERSION_MINOR = _maptitude.MAPTITUDE_VERSION_MINOR
MAPTITUDE_VERSION_PATCH = _maptitude.MAPTITUDE_VERSION_PATCH
MapOp_ADD = _maptitude.MapOp_ADD
MapOp_SUBTRACT = _maptitude.MapOp_SUBTRACT
MapOp_MIN = _maptitude.MapOp_MIN
MapOp_MAX = _maptitude.MapOp_MAX
class Residue(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    name = property(_maptitude.Residue_name_get, _maptitude.Residue_name_set)
    number = property(_maptitude.Residue_number_get, _maptitude.Residue_number_set)
    chain = property(_maptitude.Residue_chain_get, _maptitude.Residue_chain_set)
    insert_code = property(_maptitude.Residue_insert_code_get, _maptitude.Residue_insert_code_set)

    def __init__(self, *args):
        _maptitude.Residue_swiginit(self, _maptitude.new_Residue(*args))

    @staticmethod
    def FromAtom(atom):
        return _maptitude.Residue_FromAtom(atom)

    def ToString(self):
        return _maptitude.Residue_ToString(self)

    def __eq__(self, other):
        return _maptitude.Residue___eq__(self, other)

    def __ne__(self, other):
        return _maptitude.Residue___ne__(self, other)

    def __lt__(self, other):
        return _maptitude.Residue___lt__(self, other)

    def __repr__(self):
        return f"Residue('{self.ToString()}')"

    def __str__(self):
        return self.ToString()

    def __hash__(self):
        return hash((self.name, self.number, self.chain, self.insert_code))

    __swig_destroy__ = _maptitude.delete_Residue

# Register Residue in _maptitude:
_maptitude.Residue_swigregister(Residue)
class UnitCell(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    a = property(_maptitude.UnitCell_a_get, _maptitude.UnitCell_a_set)
    b = property(_maptitude.UnitCell_b_get, _maptitude.UnitCell_b_set)
    c = property(_maptitude.UnitCell_c_get, _maptitude.UnitCell_c_set)
    alpha = property(_maptitude.UnitCell_alpha_get, _maptitude.UnitCell_alpha_set)
    beta = property(_maptitude.UnitCell_beta_get, _maptitude.UnitCell_beta_set)
    gamma = property(_maptitude.UnitCell_gamma_get, _maptitude.UnitCell_gamma_set)

    def __init__(self, *args):
        _maptitude.UnitCell_swiginit(self, _maptitude.new_UnitCell(*args))

    def Volume(self):
        return _maptitude.UnitCell_Volume(self)

    def OrthogonalizationMatrix(self):
        return _maptitude.UnitCell_OrthogonalizationMatrix(self)

    def DeorthogonalizationMatrix(self):
        return _maptitude.UnitCell_DeorthogonalizationMatrix(self)

    def CartesianToFractional(self, x, y, z):
        return _maptitude.UnitCell_CartesianToFractional(self, x, y, z)

    def FractionalToCartesian(self, u, v, w):
        return _maptitude.UnitCell_FractionalToCartesian(self, u, v, w)

    def ToString(self):
        return _maptitude.UnitCell_ToString(self)

    def __eq__(self, other):
        return _maptitude.UnitCell___eq__(self, other)

    def __ne__(self, other):
        return _maptitude.UnitCell___ne__(self, other)

    def __repr__(self):
        return self.ToString()

    __swig_destroy__ = _maptitude.delete_UnitCell

# Register UnitCell in _maptitude:
_maptitude.UnitCell_swigregister(UnitCell)
class SymOp(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    R = property(_maptitude.SymOp_R_get, _maptitude.SymOp_R_set)
    t = property(_maptitude.SymOp_t_get, _maptitude.SymOp_t_set)

    def __init__(self, *args):
        _maptitude.SymOp_swiginit(self, _maptitude.new_SymOp(*args))

    @staticmethod
    def Parse(triplet):
        return _maptitude.SymOp_Parse(triplet)

    @staticmethod
    def ParseAll(text):
        return _maptitude.SymOp_ParseAll(text)

    def Apply(self, u, v, w):
        return _maptitude.SymOp_Apply(self, u, v, w)

    def ToString(self):
        return _maptitude.SymOp_ToString(self)

    def __eq__(self, other):
        return _maptitude.SymOp___eq__(self, other)

    def __ne__(self, other):
        return _maptitude.SymOp___ne__(self, other)

    def __repr__(self):
        return f"SymOp('{self.ToString()}')"

    def __str__(self):
        return self.ToString()

    __swig_destroy__ = _maptitude.delete_SymOp

# Register SymOp in _maptitude:
_maptitude.SymOp_swigregister(SymOp)
RadialSampling_FIXED = _maptitude.RadialSampling_FIXED
RadialSampling_ADAPTIVE = _maptitude.RadialSampling_ADAPTIVE
class QScoreOptions(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def SetSigma(self, sigma):
        return _maptitude.QScoreOptions_SetSigma(self, sigma)

    def GetSigma(self):
        return _maptitude.QScoreOptions_GetSigma(self)

    def SetRadialStep(self, d_rad):
        return _maptitude.QScoreOptions_SetRadialStep(self, d_rad)

    def GetRadialStep(self):
        return _maptitude.QScoreOptions_GetRadialStep(self)

    def SetMaxRadius(self, to_rad):
        return _maptitude.QScoreOptions_SetMaxRadius(self, to_rad)

    def GetMaxRadius(self):
        return _maptitude.QScoreOptions_GetMaxRadius(self)

    def SetNumPoints(self, num_points):
        return _maptitude.QScoreOptions_SetNumPoints(self, num_points)

    def GetNumPoints(self):
        return _maptitude.QScoreOptions_GetNumPoints(self)

    def SetNormalizeMap(self, normalize):
        return _maptitude.QScoreOptions_SetNormalizeMap(self, normalize)

    def GetNormalizeMap(self):
        return _maptitude.QScoreOptions_GetNormalizeMap(self)

    def SetIsolatePoints(self, isolate):
        return _maptitude.QScoreOptions_SetIsolatePoints(self, isolate)

    def GetIsolatePoints(self):
        return _maptitude.QScoreOptions_GetIsolatePoints(self)

    def SetRadialSampling(self, method):
        return _maptitude.QScoreOptions_SetRadialSampling(self, method)

    def GetRadialSampling(self):
        return _maptitude.QScoreOptions_GetRadialSampling(self)

    sigma = property(GetSigma, SetSigma)
    radial_step = property(GetRadialStep, SetRadialStep)
    max_radius = property(GetMaxRadius, SetMaxRadius)
    num_points = property(GetNumPoints, SetNumPoints)
    normalize_map = property(GetNormalizeMap, SetNormalizeMap)
    isolate_points = property(GetIsolatePoints, SetIsolatePoints)
    radial_sampling = property(GetRadialSampling, SetRadialSampling)


    def __init__(self):
        _maptitude.QScoreOptions_swiginit(self, _maptitude.new_QScoreOptions())
    __swig_destroy__ = _maptitude.delete_QScoreOptions

# Register QScoreOptions in _maptitude:
_maptitude.QScoreOptions_swigregister(QScoreOptions)
AtomRadius_FIXED = _maptitude.AtomRadius_FIXED
AtomRadius_SCALED = _maptitude.AtomRadius_SCALED
AtomRadius_BINNED = _maptitude.AtomRadius_BINNED
AtomRadius_ADAPTIVE = _maptitude.AtomRadius_ADAPTIVE
class RsccOptions(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def SetAtomRadiusMethod(self, method):
        return _maptitude.RsccOptions_SetAtomRadiusMethod(self, method)

    def GetAtomRadiusMethod(self):
        return _maptitude.RsccOptions_GetAtomRadiusMethod(self)

    def SetFixedAtomRadius(self, radius):
        return _maptitude.RsccOptions_SetFixedAtomRadius(self, radius)

    def GetFixedAtomRadius(self):
        return _maptitude.RsccOptions_GetFixedAtomRadius(self)

    def SetAtomRadiusScaling(self, scaling):
        return _maptitude.RsccOptions_SetAtomRadiusScaling(self, scaling)

    def GetAtomRadiusScaling(self):
        return _maptitude.RsccOptions_GetAtomRadiusScaling(self)

    atom_radius_method = property(GetAtomRadiusMethod, SetAtomRadiusMethod)
    fixed_atom_radius = property(GetFixedAtomRadius, SetFixedAtomRadius)
    atom_radius_scaling = property(GetAtomRadiusScaling, SetAtomRadiusScaling)


    def __init__(self):
        _maptitude.RsccOptions_swiginit(self, _maptitude.new_RsccOptions())
    __swig_destroy__ = _maptitude.delete_RsccOptions

# Register RsccOptions in _maptitude:
_maptitude.RsccOptions_swigregister(RsccOptions)
class RsrOptions(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def SetAtomRadiusMethod(self, method):
        return _maptitude.RsrOptions_SetAtomRadiusMethod(self, method)

    def GetAtomRadiusMethod(self):
        return _maptitude.RsrOptions_GetAtomRadiusMethod(self)

    def SetFixedAtomRadius(self, radius):
        return _maptitude.RsrOptions_SetFixedAtomRadius(self, radius)

    def GetFixedAtomRadius(self):
        return _maptitude.RsrOptions_GetFixedAtomRadius(self)

    def SetAtomRadiusScaling(self, scaling):
        return _maptitude.RsrOptions_SetAtomRadiusScaling(self, scaling)

    def GetAtomRadiusScaling(self):
        return _maptitude.RsrOptions_GetAtomRadiusScaling(self)

    atom_radius_method = property(GetAtomRadiusMethod, SetAtomRadiusMethod)
    fixed_atom_radius = property(GetFixedAtomRadius, SetFixedAtomRadius)
    atom_radius_scaling = property(GetAtomRadiusScaling, SetAtomRadiusScaling)


    def __init__(self):
        _maptitude.RsrOptions_swiginit(self, _maptitude.new_RsrOptions())
    __swig_destroy__ = _maptitude.delete_RsrOptions

# Register RsrOptions in _maptitude:
_maptitude.RsrOptions_swigregister(RsrOptions)
class CoverageOptions(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def SetSigma(self, sigma):
        return _maptitude.CoverageOptions_SetSigma(self, sigma)

    def GetSigma(self):
        return _maptitude.CoverageOptions_GetSigma(self)

    sigma = property(GetSigma, SetSigma)


    def __init__(self):
        _maptitude.CoverageOptions_swiginit(self, _maptitude.new_CoverageOptions())
    __swig_destroy__ = _maptitude.delete_CoverageOptions

# Register CoverageOptions in _maptitude:
_maptitude.CoverageOptions_swigregister(CoverageOptions)
class DensityScoreResult(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    overall = property(_maptitude.DensityScoreResult_overall_get, _maptitude.DensityScoreResult_overall_set)
    by_residue = property(_maptitude.DensityScoreResult_by_residue_get, _maptitude.DensityScoreResult_by_residue_set)
    by_atom = property(_maptitude.DensityScoreResult_by_atom_get, _maptitude.DensityScoreResult_by_atom_set)

    def ToString(self):
        return _maptitude.DensityScoreResult_ToString(self)

    def __repr__(self):
        return self.ToString()


    def __init__(self):
        _maptitude.DensityScoreResult_swiginit(self, _maptitude.new_DensityScoreResult())
    __swig_destroy__ = _maptitude.delete_DensityScoreResult

# Register DensityScoreResult in _maptitude:
_maptitude.DensityScoreResult_swigregister(DensityScoreResult)
class GridParams(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    x_origin = property(_maptitude.GridParams_x_origin_get, _maptitude.GridParams_x_origin_set)
    y_origin = property(_maptitude.GridParams_y_origin_get, _maptitude.GridParams_y_origin_set)
    z_origin = property(_maptitude.GridParams_z_origin_get, _maptitude.GridParams_z_origin_set)
    x_dim = property(_maptitude.GridParams_x_dim_get, _maptitude.GridParams_x_dim_set)
    y_dim = property(_maptitude.GridParams_y_dim_get, _maptitude.GridParams_y_dim_set)
    z_dim = property(_maptitude.GridParams_z_dim_get, _maptitude.GridParams_z_dim_set)
    spacing = property(_maptitude.GridParams_spacing_get, _maptitude.GridParams_spacing_set)

    def __init__(self):
        _maptitude.GridParams_swiginit(self, _maptitude.new_GridParams())
    __swig_destroy__ = _maptitude.delete_GridParams

# Register GridParams in _maptitude:
_maptitude.GridParams_swigregister(GridParams)

def get_grid_params(grid):
    return _maptitude.get_grid_params(grid)

def interpolate_density(grid, x, y, z, default_value=0.0):
    return _maptitude.interpolate_density(grid, x, y, z, default_value)

def interpolate_density_batch(grid, points, num_points, default_value=0.0):
    return _maptitude.interpolate_density_batch(grid, points, num_points, default_value)

def get_atom_grid_points(grid, x, y, z, radius):
    return _maptitude.get_atom_grid_points(grid, x, y, z, radius)

def interpolate_density_periodic(grid, x, y, z, cell_a, cell_b, cell_c, default_value=0.0):
    return _maptitude.interpolate_density_periodic(grid, x, y, z, cell_a, cell_b, cell_c, default_value)

def interpolate_density_periodic_batch(grid, points, num_points, cell_a, cell_b, cell_c, default_value=0.0):
    return _maptitude.interpolate_density_periodic_batch(grid, points, num_points, cell_a, cell_b, cell_c, default_value)
class CromerMannCoeffs(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    a = property(_maptitude.CromerMannCoeffs_a_get, _maptitude.CromerMannCoeffs_a_set)
    b = property(_maptitude.CromerMannCoeffs_b_get, _maptitude.CromerMannCoeffs_b_set)
    c = property(_maptitude.CromerMannCoeffs_c_get, _maptitude.CromerMannCoeffs_c_set)

    def Evaluate(self, s_squared):
        return _maptitude.CromerMannCoeffs_Evaluate(self, s_squared)

    def __init__(self):
        _maptitude.CromerMannCoeffs_swiginit(self, _maptitude.new_CromerMannCoeffs())
    __swig_destroy__ = _maptitude.delete_CromerMannCoeffs

# Register CromerMannCoeffs in _maptitude:
_maptitude.CromerMannCoeffs_swigregister(CromerMannCoeffs)
class ScatteringFactorEntry(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    atomic_number = property(_maptitude.ScatteringFactorEntry_atomic_number_get, _maptitude.ScatteringFactorEntry_atomic_number_set)
    formal_charge = property(_maptitude.ScatteringFactorEntry_formal_charge_get, _maptitude.ScatteringFactorEntry_formal_charge_set)
    coeffs = property(_maptitude.ScatteringFactorEntry_coeffs_get, _maptitude.ScatteringFactorEntry_coeffs_set)

    def __init__(self):
        _maptitude.ScatteringFactorEntry_swiginit(self, _maptitude.new_ScatteringFactorEntry())
    __swig_destroy__ = _maptitude.delete_ScatteringFactorEntry

# Register ScatteringFactorEntry in _maptitude:
_maptitude.ScatteringFactorEntry_swigregister(ScatteringFactorEntry)

def get_scattering_factors(atomic_number, formal_charge=0):
    return _maptitude.get_scattering_factors(atomic_number, formal_charge)
class DensityCalculator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, cell, symops):
        _maptitude.DensityCalculator_swiginit(self, _maptitude.new_DensityCalculator(cell, symops))
    __swig_destroy__ = _maptitude.delete_DensityCalculator

    def Calculate(self, mol, obs_grid, resolution, mask=None, k_sol=0.35, b_sol=46.0, include_h=False, n_scale_shells=1):
        return _maptitude.DensityCalculator_Calculate(self, mol, obs_grid, resolution, mask, k_sol, b_sol, include_h, n_scale_shells)

# Register DensityCalculator in _maptitude:
_maptitude.DensityCalculator_swigregister(DensityCalculator)

def rscc(*args):
    return _maptitude.rscc(*args)

def rsr(*args):
    return _maptitude.rsr(*args)

def qscore(*args):
    return _maptitude.qscore(*args)

def ediam(mol, grid, resolution, mask=None):
    return _maptitude.ediam(mol, grid, resolution, mask)

def coverage(*args):
    return _maptitude.coverage(*args)

def scale_map(grid, factor):
    return _maptitude.scale_map(grid, factor)

def combine_maps(lhs, rhs, op):
    return _maptitude.combine_maps(lhs, rhs, op)

def diff_to_calc(obs_grid, diff_grid):
    return _maptitude.diff_to_calc(obs_grid, diff_grid)

def wrap_and_pad_grid(grid, mol, cell_a, cell_b, cell_c, padding=3.0):
    return _maptitude.wrap_and_pad_grid(grid, mol, cell_a, cell_b, cell_c, padding)

def _get_scattering_factor_table_vec():
    return _maptitude._get_scattering_factor_table_vec()
class ScatteringFactorEntryVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _maptitude.ScatteringFactorEntryVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _maptitude.ScatteringFactorEntryVector___nonzero__(self)

    def __bool__(self):
        return _maptitude.ScatteringFactorEntryVector___bool__(self)

    def __len__(self):
        return _maptitude.ScatteringFactorEntryVector___len__(self)

    def __getslice__(self, i, j):
        return _maptitude.ScatteringFactorEntryVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _maptitude.ScatteringFactorEntryVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _maptitude.ScatteringFactorEntryVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _maptitude.ScatteringFactorEntryVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _maptitude.ScatteringFactorEntryVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _maptitude.ScatteringFactorEntryVector___setitem__(self, *args)

    def pop(self):
        return _maptitude.ScatteringFactorEntryVector_pop(self)

    def append(self, x):
        return _maptitude.ScatteringFactorEntryVector_append(self, x)

    def empty(self):
        return _maptitude.ScatteringFactorEntryVector_empty(self)

    def size(self):
        return _maptitude.ScatteringFactorEntryVector_size(self)

    def swap(self, v):
        return _maptitude.ScatteringFactorEntryVector_swap(self, v)

    def begin(self):
        return _maptitude.ScatteringFactorEntryVector_begin(self)

    def end(self):
        return _maptitude.ScatteringFactorEntryVector_end(self)

    def rbegin(self):
        return _maptitude.ScatteringFactorEntryVector_rbegin(self)

    def rend(self):
        return _maptitude.ScatteringFactorEntryVector_rend(self)

    def clear(self):
        return _maptitude.ScatteringFactorEntryVector_clear(self)

    def get_allocator(self):
        return _maptitude.ScatteringFactorEntryVector_get_allocator(self)

    def pop_back(self):
        return _maptitude.ScatteringFactorEntryVector_pop_back(self)

    def erase(self, *args):
        return _maptitude.ScatteringFactorEntryVector_erase(self, *args)

    def __init__(self, *args):
        _maptitude.ScatteringFactorEntryVector_swiginit(self, _maptitude.new_ScatteringFactorEntryVector(*args))

    def push_back(self, x):
        return _maptitude.ScatteringFactorEntryVector_push_back(self, x)

    def front(self):
        return _maptitude.ScatteringFactorEntryVector_front(self)

    def back(self):
        return _maptitude.ScatteringFactorEntryVector_back(self)

    def assign(self, n, x):
        return _maptitude.ScatteringFactorEntryVector_assign(self, n, x)

    def resize(self, *args):
        return _maptitude.ScatteringFactorEntryVector_resize(self, *args)

    def insert(self, *args):
        return _maptitude.ScatteringFactorEntryVector_insert(self, *args)

    def reserve(self, n):
        return _maptitude.ScatteringFactorEntryVector_reserve(self, n)

    def capacity(self):
        return _maptitude.ScatteringFactorEntryVector_capacity(self)
    __swig_destroy__ = _maptitude.delete_ScatteringFactorEntryVector

# Register ScatteringFactorEntryVector in _maptitude:
_maptitude.ScatteringFactorEntryVector_swigregister(ScatteringFactorEntryVector)

# Save references to SWIG-generated C++ wrappers before overriding
_cpp_rscc = rscc
_cpp_rsr = rsr
_cpp_qscore = qscore
_cpp_ediam = ediam
_cpp_coverage = coverage
_cpp_scale_map = scale_map
_cpp_combine_maps = combine_maps
_cpp_diff_to_calc = diff_to_calc
_cpp_wrap_and_pad_grid = wrap_and_pad_grid


def fc_density(obj, obs_grid, resolution, cell, mask=None,
               k_sol=0.35, b_sol=46.0, symops=None,
               include_h=False, n_scale_shells=1):
    """Compute model electron density via Fourier synthesis.

    :param obj: Input molecule (OEMolBase or OEDesignUnit).
    :param obs_grid: Observed electron density grid (OEScalarGrid).
    :param resolution: Resolution limit in Angstroms.
    :param cell: UnitCell parameters.
    :param mask: Optional atom predicate to restrict contributing atoms.
    :param k_sol: Bulk solvent scale factor (default: 0.35 e/A^3).
    :param b_sol: Bulk solvent B-factor (default: 46.0 A^2).
    :param symops: List of SymOp or string of symmetry operators.
    :param include_h: Include hydrogen atoms (default: False).
    :param n_scale_shells: Number of per-shell scaling bins (default: 1).
    :returns: OEScalarGrid with computed model density.
    """
    if symops is None:
        symops = [SymOp()]  # Identity only
    elif isinstance(symops, str):
        symops = list(SymOp.ParseAll(symops))

    if isinstance(symops, list) and len(symops) > 0 and not isinstance(symops[0], SymOp):
# Convert from SymOpVector if needed
        symops = list(symops)

    calc = DensityCalculator(cell, SymOpVector(symops))
    return calc.Calculate(obj, obs_grid, resolution, mask,
                          k_sol, b_sol, include_h, n_scale_shells)


def rscc(obj, grid, resolution, mask=None, calc_grid=None,
         atom_radius=None, options=None):
    """Real-Space Correlation Coefficient.

    :param obj: Input molecule.
    :param grid: Observed electron density map.
    :param resolution: Resolution in Angstroms.
    :param mask: Optional atom predicate.
    :param calc_grid: Optional pre-computed calculated density.
    :param atom_radius: Atom radius method (str or AtomRadius enum value).
    :param options: RsccOptions configuration object.
    :returns: DensityScoreResult with RSCC values.
    """
    if options is None:
        options = RsccOptions()
    if atom_radius is not None:
        if isinstance(atom_radius, str):
            _radius_map = {
                "fixed": AtomRadius_FIXED,
                "scaled": AtomRadius_SCALED,
                "binned": AtomRadius_BINNED,
            }
            atom_radius = _radius_map[atom_radius.lower()]
        options.SetAtomRadiusMethod(atom_radius)
    return _cpp_rscc(obj, grid, resolution, mask, calc_grid, options)


def rsr(obj, grid, resolution, mask=None, calc_grid=None,
        atom_radius=None, options=None):
    """Real-Space R-Factor.

    :param obj: Input molecule.
    :param grid: Observed electron density map.
    :param resolution: Resolution in Angstroms.
    :param mask: Optional atom predicate.
    :param calc_grid: Optional pre-computed calculated density.
    :param atom_radius: Atom radius method (str or AtomRadius enum value).
    :param options: RsrOptions configuration object.
    :returns: DensityScoreResult with RSR values.
    """
    if options is None:
        options = RsrOptions()
    if atom_radius is not None:
        if isinstance(atom_radius, str):
            _radius_map = {
                "fixed": AtomRadius_FIXED,
                "scaled": AtomRadius_SCALED,
                "binned": AtomRadius_BINNED,
                "adaptive": AtomRadius_ADAPTIVE,
            }
            atom_radius = _radius_map[atom_radius.lower()]
        options.SetAtomRadiusMethod(atom_radius)
    return _cpp_rsr(obj, grid, resolution, mask, calc_grid, options)


def qscore(obj, grid, resolution, mask=None, options=None):
    """Q-Score (Pintilie et al., 2020).

    :param obj: Input molecule.
    :param grid: Observed electron density map.
    :param resolution: Resolution in Angstroms.
    :param mask: Optional atom predicate.
    :param options: QScoreOptions configuration.
    :returns: DensityScoreResult with Q-score values.
    """
    if options is None:
        options = QScoreOptions()
    return _cpp_qscore(obj, grid, resolution, mask, options)


def ediam(obj, grid, resolution, mask=None):
    """Electron Density Index Averaged, Modified (EDIAm).

    :param obj: Input molecule.
    :param grid: Observed electron density map.
    :param resolution: Resolution in Angstroms.
    :param mask: Optional atom predicate.
    :returns: DensityScoreResult with EDIAm values in [0, 1].
    """
    return _cpp_ediam(obj, grid, resolution, mask)


def coverage(obj, grid, sigma=1.0, mask=None, options=None):
    """Coverage: fraction of atoms observed in density.

    :param obj: Input molecule.
    :param grid: Observed electron density map.
    :param sigma: Number of standard deviations above mean.
    :param mask: Optional atom predicate.
    :param options: CoverageOptions configuration object.
    :returns: DensityScoreResult with coverage fractions.
    """
    if options is None:
        options = CoverageOptions()
    if sigma != 1.0:
        options.SetSigma(sigma)
    return _cpp_coverage(obj, grid, mask, options)


def parse_symop(s):
    """Parse a single symmetry operator from triplet notation.

    :param s: Symmetry operator string (e.g., "x,y,z" or "-x,y+1/2,-z").
    :returns: SymOp object.
    """
    return SymOp.Parse(s)


def parse_symops(text):
    """Parse multiple symmetry operators from newline/semicolon-separated text.

    :param text: Block of symmetry operators.
    :returns: List of SymOp objects.
    """
    return list(SymOp.ParseAll(text))


def scale_map(grid, factor):
    """Scale a grid by multiplying all values by a scalar.

    :param grid: Grid to scale (modified in place).
    :param factor: Scale factor.
    """
    _cpp_scale_map(grid, factor)


def combine_maps(lhs, rhs, op):
    """Combine two grids element-wise.

    :param lhs: Left-hand side grid.
    :param rhs: Right-hand side grid.
    :param op: MapOp enum value (ADD, SUBTRACT, MIN, MAX).
    :returns: New OEScalarGrid with combined values.
    """
    return _cpp_combine_maps(lhs, rhs, op)


def diff_to_calc(obs_grid, diff_grid):
    """Derive calculated density from observed and difference maps.

    :param obs_grid: Observed density map (2mFo-DFc).
    :param diff_grid: Difference density map (mFo-DFc).
    :returns: New OEScalarGrid with calculated density.
    """
    return _cpp_diff_to_calc(obs_grid, diff_grid)


def wrap_and_pad_grid(grid, mol, cell_a, cell_b, cell_c, padding=3.0):
    """Translate molecule into unit cell and pad grid if needed.

    :param grid: CCP4 unit-cell grid.
    :param mol: Molecule to wrap (modified in-place).
    :param cell_a: Unit cell dimension a (Angstroms).
    :param cell_b: Unit cell dimension b (Angstroms).
    :param cell_c: Unit cell dimension c (Angstroms).
    :param padding: Extra margin around atoms (Angstroms).
    :returns: Grid covering all atom coordinates (original or padded).
    """
    result = _cpp_wrap_and_pad_grid(grid, mol, cell_a, cell_b, cell_c, padding)
    return result if result is not None else grid


def get_scattering_factor_table():
    """Get the full scattering factor table.

    :returns: Tuple of (table_entries, count).
    """
    entries = _get_scattering_factor_table_vec()
    return entries, len(entries)


__version__ = "0.1.0"


