# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.5.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

import typing
# Import the low-level C/C++ module
if getattr(globals().get("__spec__"), "parent", None) or __package__ or "." in __name__:
    from . import _maptitude
else:
    import _maptitude

import builtins as __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _maptitude.delete_SwigPyIterator

    def value(self):
        return _maptitude.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _maptitude.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _maptitude.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _maptitude.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _maptitude.SwigPyIterator_equal(self, x)

    def copy(self):
        return _maptitude.SwigPyIterator_copy(self)

    def __next__(self):
        return _maptitude.SwigPyIterator___next__(self)

    def previous(self):
        return _maptitude.SwigPyIterator_previous(self)

    def advance(self, n):
        return _maptitude.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _maptitude.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _maptitude.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _maptitude.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _maptitude.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _maptitude.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _maptitude.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _maptitude:
_maptitude.SwigPyIterator_swigregister(SwigPyIterator)

# The exception classes are created in the extension module's init function.
# SWIG's proxy module does not mirror arbitrary extension attributes, so alias
# them here; python/maptitude/__init__.py re-exports from this module.
MaptitudeError = _maptitude.MaptitudeError
StructureError = _maptitude.StructureError
GridError = _maptitude.GridError
SymOpError = _maptitude.SymOpError
CellError = _maptitude.CellError

class DoubleVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _maptitude.DoubleVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __bool__(self):
        return _maptitude.DoubleVector___bool__(self)

    def __len__(self):
        return _maptitude.DoubleVector___len__(self)

    def __delitem__(self, *args):
        return _maptitude.DoubleVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _maptitude.DoubleVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _maptitude.DoubleVector___setitem__(self, *args)

    def pop(self):
        return _maptitude.DoubleVector_pop(self)

    def append(self, x):
        return _maptitude.DoubleVector_append(self, x)

    def empty(self):
        return _maptitude.DoubleVector_empty(self)

    def size(self):
        return _maptitude.DoubleVector_size(self)

    def swap(self, v):
        return _maptitude.DoubleVector_swap(self, v)

    def begin(self):
        return _maptitude.DoubleVector_begin(self)

    def end(self):
        return _maptitude.DoubleVector_end(self)

    def rbegin(self):
        return _maptitude.DoubleVector_rbegin(self)

    def rend(self):
        return _maptitude.DoubleVector_rend(self)

    def clear(self):
        return _maptitude.DoubleVector_clear(self)

    def get_allocator(self):
        return _maptitude.DoubleVector_get_allocator(self)

    def pop_back(self):
        return _maptitude.DoubleVector_pop_back(self)

    def erase(self, *args):
        return _maptitude.DoubleVector_erase(self, *args)

    def __init__(self, *args):
        _maptitude.DoubleVector_swiginit(self, _maptitude.new_DoubleVector(*args))

    def push_back(self, x):
        return _maptitude.DoubleVector_push_back(self, x)

    def front(self):
        return _maptitude.DoubleVector_front(self)

    def back(self):
        return _maptitude.DoubleVector_back(self)

    def assign(self, n, x):
        return _maptitude.DoubleVector_assign(self, n, x)

    def resize(self, *args):
        return _maptitude.DoubleVector_resize(self, *args)

    def insert(self, *args):
        return _maptitude.DoubleVector_insert(self, *args)

    def reserve(self, n):
        return _maptitude.DoubleVector_reserve(self, n)

    def capacity(self):
        return _maptitude.DoubleVector_capacity(self)
    __swig_destroy__ = _maptitude.delete_DoubleVector

# Register DoubleVector in _maptitude:
_maptitude.DoubleVector_swigregister(DoubleVector)
class UnsignedIntVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _maptitude.UnsignedIntVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __bool__(self):
        return _maptitude.UnsignedIntVector___bool__(self)

    def __len__(self):
        return _maptitude.UnsignedIntVector___len__(self)

    def __delitem__(self, *args):
        return _maptitude.UnsignedIntVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _maptitude.UnsignedIntVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _maptitude.UnsignedIntVector___setitem__(self, *args)

    def pop(self):
        return _maptitude.UnsignedIntVector_pop(self)

    def append(self, x):
        return _maptitude.UnsignedIntVector_append(self, x)

    def empty(self):
        return _maptitude.UnsignedIntVector_empty(self)

    def size(self):
        return _maptitude.UnsignedIntVector_size(self)

    def swap(self, v):
        return _maptitude.UnsignedIntVector_swap(self, v)

    def begin(self):
        return _maptitude.UnsignedIntVector_begin(self)

    def end(self):
        return _maptitude.UnsignedIntVector_end(self)

    def rbegin(self):
        return _maptitude.UnsignedIntVector_rbegin(self)

    def rend(self):
        return _maptitude.UnsignedIntVector_rend(self)

    def clear(self):
        return _maptitude.UnsignedIntVector_clear(self)

    def get_allocator(self):
        return _maptitude.UnsignedIntVector_get_allocator(self)

    def pop_back(self):
        return _maptitude.UnsignedIntVector_pop_back(self)

    def erase(self, *args):
        return _maptitude.UnsignedIntVector_erase(self, *args)

    def __init__(self, *args):
        _maptitude.UnsignedIntVector_swiginit(self, _maptitude.new_UnsignedIntVector(*args))

    def push_back(self, x):
        return _maptitude.UnsignedIntVector_push_back(self, x)

    def front(self):
        return _maptitude.UnsignedIntVector_front(self)

    def back(self):
        return _maptitude.UnsignedIntVector_back(self)

    def assign(self, n, x):
        return _maptitude.UnsignedIntVector_assign(self, n, x)

    def resize(self, *args):
        return _maptitude.UnsignedIntVector_resize(self, *args)

    def insert(self, *args):
        return _maptitude.UnsignedIntVector_insert(self, *args)

    def reserve(self, n):
        return _maptitude.UnsignedIntVector_reserve(self, n)

    def capacity(self):
        return _maptitude.UnsignedIntVector_capacity(self)
    __swig_destroy__ = _maptitude.delete_UnsignedIntVector

# Register UnsignedIntVector in _maptitude:
_maptitude.UnsignedIntVector_swigregister(UnsignedIntVector)
class SymOpVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _maptitude.SymOpVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __bool__(self):
        return _maptitude.SymOpVector___bool__(self)

    def __len__(self):
        return _maptitude.SymOpVector___len__(self)

    def __delitem__(self, *args):
        return _maptitude.SymOpVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _maptitude.SymOpVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _maptitude.SymOpVector___setitem__(self, *args)

    def pop(self):
        return _maptitude.SymOpVector_pop(self)

    def append(self, x):
        return _maptitude.SymOpVector_append(self, x)

    def empty(self):
        return _maptitude.SymOpVector_empty(self)

    def size(self):
        return _maptitude.SymOpVector_size(self)

    def swap(self, v):
        return _maptitude.SymOpVector_swap(self, v)

    def begin(self):
        return _maptitude.SymOpVector_begin(self)

    def end(self):
        return _maptitude.SymOpVector_end(self)

    def rbegin(self):
        return _maptitude.SymOpVector_rbegin(self)

    def rend(self):
        return _maptitude.SymOpVector_rend(self)

    def clear(self):
        return _maptitude.SymOpVector_clear(self)

    def get_allocator(self):
        return _maptitude.SymOpVector_get_allocator(self)

    def pop_back(self):
        return _maptitude.SymOpVector_pop_back(self)

    def erase(self, *args):
        return _maptitude.SymOpVector_erase(self, *args)

    def __init__(self, *args):
        _maptitude.SymOpVector_swiginit(self, _maptitude.new_SymOpVector(*args))

    def push_back(self, x):
        return _maptitude.SymOpVector_push_back(self, x)

    def front(self):
        return _maptitude.SymOpVector_front(self)

    def back(self):
        return _maptitude.SymOpVector_back(self)

    def assign(self, n, x):
        return _maptitude.SymOpVector_assign(self, n, x)

    def resize(self, *args):
        return _maptitude.SymOpVector_resize(self, *args)

    def insert(self, *args):
        return _maptitude.SymOpVector_insert(self, *args)

    def reserve(self, n):
        return _maptitude.SymOpVector_reserve(self, n)

    def capacity(self):
        return _maptitude.SymOpVector_capacity(self)
    __swig_destroy__ = _maptitude.delete_SymOpVector

# Register SymOpVector in _maptitude:
_maptitude.SymOpVector_swigregister(SymOpVector)
class ResidueDoubleMap(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _maptitude.ResidueDoubleMap_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __bool__(self):
        return _maptitude.ResidueDoubleMap___bool__(self)

    def __len__(self):
        return _maptitude.ResidueDoubleMap___len__(self)
    def __iter__(self):
        return self.key_iterator()
    def iterkeys(self):
        return self.key_iterator()
    def itervalues(self):
        return self.value_iterator()
    def iteritems(self):
        return self.iterator()

    def __getitem__(self, key):
        return _maptitude.ResidueDoubleMap___getitem__(self, key)

    def __delitem__(self, key):
        return _maptitude.ResidueDoubleMap___delitem__(self, key)

    def has_key(self, key):
        return _maptitude.ResidueDoubleMap_has_key(self, key)

    def keys(self):
        return _maptitude.ResidueDoubleMap_keys(self)

    def values(self):
        return _maptitude.ResidueDoubleMap_values(self)

    def items(self):
        return _maptitude.ResidueDoubleMap_items(self)

    def __contains__(self, key):
        return _maptitude.ResidueDoubleMap___contains__(self, key)

    def key_iterator(self):
        return _maptitude.ResidueDoubleMap_key_iterator(self)

    def value_iterator(self):
        return _maptitude.ResidueDoubleMap_value_iterator(self)

    def __setitem__(self, *args):
        return _maptitude.ResidueDoubleMap___setitem__(self, *args)

    def asdict(self):
        return _maptitude.ResidueDoubleMap_asdict(self)

    def __init__(self, *args):
        _maptitude.ResidueDoubleMap_swiginit(self, _maptitude.new_ResidueDoubleMap(*args))

    def empty(self):
        return _maptitude.ResidueDoubleMap_empty(self)

    def size(self):
        return _maptitude.ResidueDoubleMap_size(self)

    def swap(self, v):
        return _maptitude.ResidueDoubleMap_swap(self, v)

    def begin(self):
        return _maptitude.ResidueDoubleMap_begin(self)

    def end(self):
        return _maptitude.ResidueDoubleMap_end(self)

    def rbegin(self):
        return _maptitude.ResidueDoubleMap_rbegin(self)

    def rend(self):
        return _maptitude.ResidueDoubleMap_rend(self)

    def clear(self):
        return _maptitude.ResidueDoubleMap_clear(self)

    def get_allocator(self):
        return _maptitude.ResidueDoubleMap_get_allocator(self)

    def count(self, x):
        return _maptitude.ResidueDoubleMap_count(self, x)

    def erase(self, *args):
        return _maptitude.ResidueDoubleMap_erase(self, *args)

    def find(self, x):
        return _maptitude.ResidueDoubleMap_find(self, x)

    def lower_bound(self, x):
        return _maptitude.ResidueDoubleMap_lower_bound(self, x)

    def upper_bound(self, x):
        return _maptitude.ResidueDoubleMap_upper_bound(self, x)
    __swig_destroy__ = _maptitude.delete_ResidueDoubleMap

# Register ResidueDoubleMap in _maptitude:
_maptitude.ResidueDoubleMap_swigregister(ResidueDoubleMap)
class UIntDoubleMap(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _maptitude.UIntDoubleMap_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __bool__(self):
        return _maptitude.UIntDoubleMap___bool__(self)

    def __len__(self):
        return _maptitude.UIntDoubleMap___len__(self)
    def __iter__(self):
        return self.key_iterator()
    def iterkeys(self):
        return self.key_iterator()
    def itervalues(self):
        return self.value_iterator()
    def iteritems(self):
        return self.iterator()

    def __getitem__(self, key):
        return _maptitude.UIntDoubleMap___getitem__(self, key)

    def __delitem__(self, key):
        return _maptitude.UIntDoubleMap___delitem__(self, key)

    def has_key(self, key):
        return _maptitude.UIntDoubleMap_has_key(self, key)

    def keys(self):
        return _maptitude.UIntDoubleMap_keys(self)

    def values(self):
        return _maptitude.UIntDoubleMap_values(self)

    def items(self):
        return _maptitude.UIntDoubleMap_items(self)

    def __contains__(self, key):
        return _maptitude.UIntDoubleMap___contains__(self, key)

    def key_iterator(self):
        return _maptitude.UIntDoubleMap_key_iterator(self)

    def value_iterator(self):
        return _maptitude.UIntDoubleMap_value_iterator(self)

    def __setitem__(self, *args):
        return _maptitude.UIntDoubleMap___setitem__(self, *args)

    def asdict(self):
        return _maptitude.UIntDoubleMap_asdict(self)

    def __init__(self, *args):
        _maptitude.UIntDoubleMap_swiginit(self, _maptitude.new_UIntDoubleMap(*args))

    def empty(self):
        return _maptitude.UIntDoubleMap_empty(self)

    def size(self):
        return _maptitude.UIntDoubleMap_size(self)

    def swap(self, v):
        return _maptitude.UIntDoubleMap_swap(self, v)

    def begin(self):
        return _maptitude.UIntDoubleMap_begin(self)

    def end(self):
        return _maptitude.UIntDoubleMap_end(self)

    def rbegin(self):
        return _maptitude.UIntDoubleMap_rbegin(self)

    def rend(self):
        return _maptitude.UIntDoubleMap_rend(self)

    def clear(self):
        return _maptitude.UIntDoubleMap_clear(self)

    def get_allocator(self):
        return _maptitude.UIntDoubleMap_get_allocator(self)

    def count(self, x):
        return _maptitude.UIntDoubleMap_count(self, x)

    def erase(self, *args):
        return _maptitude.UIntDoubleMap_erase(self, *args)

    def find(self, x):
        return _maptitude.UIntDoubleMap_find(self, x)

    def lower_bound(self, x):
        return _maptitude.UIntDoubleMap_lower_bound(self, x)

    def upper_bound(self, x):
        return _maptitude.UIntDoubleMap_upper_bound(self, x)
    __swig_destroy__ = _maptitude.delete_UIntDoubleMap

# Register UIntDoubleMap in _maptitude:
_maptitude.UIntDoubleMap_swigregister(UIntDoubleMap)
class Double3Array(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _maptitude.Double3Array_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __bool__(self):
        return _maptitude.Double3Array___bool__(self)

    def __len__(self):
        return _maptitude.Double3Array___len__(self)

    def __delitem__(self, *args):
        return _maptitude.Double3Array___delitem__(self, *args)

    def __getitem__(self, *args):
        return _maptitude.Double3Array___getitem__(self, *args)

    def __setitem__(self, *args):
        return _maptitude.Double3Array___setitem__(self, *args)

    def __init__(self, *args):
        _maptitude.Double3Array_swiginit(self, _maptitude.new_Double3Array(*args))

    def empty(self):
        return _maptitude.Double3Array_empty(self)

    def size(self):
        return _maptitude.Double3Array_size(self)

    def swap(self, v):
        return _maptitude.Double3Array_swap(self, v)

    def begin(self):
        return _maptitude.Double3Array_begin(self)

    def end(self):
        return _maptitude.Double3Array_end(self)

    def rbegin(self):
        return _maptitude.Double3Array_rbegin(self)

    def rend(self):
        return _maptitude.Double3Array_rend(self)

    def front(self):
        return _maptitude.Double3Array_front(self)

    def back(self):
        return _maptitude.Double3Array_back(self)

    def fill(self, u):
        return _maptitude.Double3Array_fill(self, u)
    __swig_destroy__ = _maptitude.delete_Double3Array

# Register Double3Array in _maptitude:
_maptitude.Double3Array_swigregister(Double3Array)
class Double9Array(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _maptitude.Double9Array_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __bool__(self):
        return _maptitude.Double9Array___bool__(self)

    def __len__(self):
        return _maptitude.Double9Array___len__(self)

    def __delitem__(self, *args):
        return _maptitude.Double9Array___delitem__(self, *args)

    def __getitem__(self, *args):
        return _maptitude.Double9Array___getitem__(self, *args)

    def __setitem__(self, *args):
        return _maptitude.Double9Array___setitem__(self, *args)

    def __init__(self, *args):
        _maptitude.Double9Array_swiginit(self, _maptitude.new_Double9Array(*args))

    def empty(self):
        return _maptitude.Double9Array_empty(self)

    def size(self):
        return _maptitude.Double9Array_size(self)

    def swap(self, v):
        return _maptitude.Double9Array_swap(self, v)

    def begin(self):
        return _maptitude.Double9Array_begin(self)

    def end(self):
        return _maptitude.Double9Array_end(self)

    def rbegin(self):
        return _maptitude.Double9Array_rbegin(self)

    def rend(self):
        return _maptitude.Double9Array_rend(self)

    def front(self):
        return _maptitude.Double9Array_front(self)

    def back(self):
        return _maptitude.Double9Array_back(self)

    def fill(self, u):
        return _maptitude.Double9Array_fill(self, u)
    __swig_destroy__ = _maptitude.delete_Double9Array

# Register Double9Array in _maptitude:
_maptitude.Double9Array_swigregister(Double9Array)
MAPTITUDE_VERSION_MAJOR = _maptitude.MAPTITUDE_VERSION_MAJOR
MAPTITUDE_VERSION_MINOR = _maptitude.MAPTITUDE_VERSION_MINOR
MAPTITUDE_VERSION_PATCH = _maptitude.MAPTITUDE_VERSION_PATCH
MapOp_ADD = _maptitude.MapOp_ADD
MapOp_SUBTRACT = _maptitude.MapOp_SUBTRACT
MapOp_MIN = _maptitude.MapOp_MIN
MapOp_MAX = _maptitude.MapOp_MAX
OriginSource_ORIGIN_RECORD = _maptitude.OriginSource_ORIGIN_RECORD
OriginSource_NXSTART = _maptitude.OriginSource_NXSTART
class Residue(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    name = property(_maptitude.Residue_name_get, _maptitude.Residue_name_set)
    number = property(_maptitude.Residue_number_get, _maptitude.Residue_number_set)
    chain = property(_maptitude.Residue_chain_get, _maptitude.Residue_chain_set)
    insert_code = property(_maptitude.Residue_insert_code_get, _maptitude.Residue_insert_code_set)

    def __init__(self, *args):
        _maptitude.Residue_swiginit(self, _maptitude.new_Residue(*args))

    @staticmethod
    def FromAtom(atom):
        return _maptitude.Residue_FromAtom(atom)

    def ToString(self):
        return _maptitude.Residue_ToString(self)

    def __eq__(self, other):
        return _maptitude.Residue___eq__(self, other)

    def __ne__(self, other):
        return _maptitude.Residue___ne__(self, other)

    def __lt__(self, other):
        return _maptitude.Residue___lt__(self, other)

    def __repr__(self):
        return f"Residue('{self.ToString()}')"

    def __str__(self):
        return self.ToString()

    def __hash__(self):
        return hash((self.name, self.number, self.chain, self.insert_code))

    __swig_destroy__ = _maptitude.delete_Residue

# Register Residue in _maptitude:
_maptitude.Residue_swigregister(Residue)
class UnitCell(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    a = property(_maptitude.UnitCell_a_get, _maptitude.UnitCell_a_set)
    b = property(_maptitude.UnitCell_b_get, _maptitude.UnitCell_b_set)
    c = property(_maptitude.UnitCell_c_get, _maptitude.UnitCell_c_set)
    alpha = property(_maptitude.UnitCell_alpha_get, _maptitude.UnitCell_alpha_set)
    beta = property(_maptitude.UnitCell_beta_get, _maptitude.UnitCell_beta_set)
    gamma = property(_maptitude.UnitCell_gamma_get, _maptitude.UnitCell_gamma_set)

    def __init__(self, *args):
        _maptitude.UnitCell_swiginit(self, _maptitude.new_UnitCell(*args))

    def Volume(self):
        return _maptitude.UnitCell_Volume(self)

    def OrthogonalizationMatrix(self):
        return _maptitude.UnitCell_OrthogonalizationMatrix(self)

    def DeorthogonalizationMatrix(self):
        return _maptitude.UnitCell_DeorthogonalizationMatrix(self)

    def CartesianToFractional(self, x, y, z):
        return _maptitude.UnitCell_CartesianToFractional(self, x, y, z)

    def FractionalToCartesian(self, u, v, w):
        return _maptitude.UnitCell_FractionalToCartesian(self, u, v, w)

    def ToString(self):
        return _maptitude.UnitCell_ToString(self)

    def __eq__(self, other):
        return _maptitude.UnitCell___eq__(self, other)

    def __ne__(self, other):
        return _maptitude.UnitCell___ne__(self, other)

    def __repr__(self):
        return self.ToString()

    __swig_destroy__ = _maptitude.delete_UnitCell

# Register UnitCell in _maptitude:
_maptitude.UnitCell_swigregister(UnitCell)
class SymOp(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    R = property(_maptitude.SymOp_R_get, _maptitude.SymOp_R_set)
    t = property(_maptitude.SymOp_t_get, _maptitude.SymOp_t_set)

    def __init__(self, *args):
        _maptitude.SymOp_swiginit(self, _maptitude.new_SymOp(*args))

    @staticmethod
    def Parse(triplet):
        return _maptitude.SymOp_Parse(triplet)

    @staticmethod
    def ParseAll(text):
        return _maptitude.SymOp_ParseAll(text)

    def Apply(self, u, v, w):
        return _maptitude.SymOp_Apply(self, u, v, w)

    def ToString(self):
        return _maptitude.SymOp_ToString(self)

    def __eq__(self, other):
        return _maptitude.SymOp___eq__(self, other)

    def __ne__(self, other):
        return _maptitude.SymOp___ne__(self, other)

    def __repr__(self):
        return f"SymOp('{self.ToString()}')"

    def __str__(self):
        return self.ToString()

    __swig_destroy__ = _maptitude.delete_SymOp

# Register SymOp in _maptitude:
_maptitude.SymOp_swigregister(SymOp)
RadialSampling_FIXED = _maptitude.RadialSampling_FIXED
RadialSampling_ADAPTIVE = _maptitude.RadialSampling_ADAPTIVE
class QScoreOptions(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def SetSigma(self, sigma):
        return _maptitude.QScoreOptions_SetSigma(self, sigma)

    def GetSigma(self):
        return _maptitude.QScoreOptions_GetSigma(self)

    def SetRadialStep(self, d_rad):
        return _maptitude.QScoreOptions_SetRadialStep(self, d_rad)

    def GetRadialStep(self):
        return _maptitude.QScoreOptions_GetRadialStep(self)

    def SetMaxRadius(self, to_rad):
        return _maptitude.QScoreOptions_SetMaxRadius(self, to_rad)

    def GetMaxRadius(self):
        return _maptitude.QScoreOptions_GetMaxRadius(self)

    def SetNumPoints(self, num_points):
        return _maptitude.QScoreOptions_SetNumPoints(self, num_points)

    def GetNumPoints(self):
        return _maptitude.QScoreOptions_GetNumPoints(self)

    def SetNormalizeMap(self, normalize):
        return _maptitude.QScoreOptions_SetNormalizeMap(self, normalize)

    def GetNormalizeMap(self):
        return _maptitude.QScoreOptions_GetNormalizeMap(self)

    def SetIsolatePoints(self, isolate):
        return _maptitude.QScoreOptions_SetIsolatePoints(self, isolate)

    def GetIsolatePoints(self):
        return _maptitude.QScoreOptions_GetIsolatePoints(self)

    def SetRadialSampling(self, method):
        return _maptitude.QScoreOptions_SetRadialSampling(self, method)

    def GetRadialSampling(self):
        return _maptitude.QScoreOptions_GetRadialSampling(self)

    sigma = property(GetSigma, SetSigma)
    radial_step = property(GetRadialStep, SetRadialStep)
    max_radius = property(GetMaxRadius, SetMaxRadius)
    num_points = property(GetNumPoints, SetNumPoints)
    normalize_map = property(GetNormalizeMap, SetNormalizeMap)
    isolate_points = property(GetIsolatePoints, SetIsolatePoints)
    radial_sampling = property(GetRadialSampling, SetRadialSampling)


    def __init__(self):
        _maptitude.QScoreOptions_swiginit(self, _maptitude.new_QScoreOptions())
    __swig_destroy__ = _maptitude.delete_QScoreOptions

# Register QScoreOptions in _maptitude:
_maptitude.QScoreOptions_swigregister(QScoreOptions)
AtomRadius_FIXED = _maptitude.AtomRadius_FIXED
AtomRadius_SCALED = _maptitude.AtomRadius_SCALED
AtomRadius_BINNED = _maptitude.AtomRadius_BINNED
AtomRadius_ADAPTIVE = _maptitude.AtomRadius_ADAPTIVE
class RsccOptions(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def SetAtomRadiusMethod(self, method):
        return _maptitude.RsccOptions_SetAtomRadiusMethod(self, method)

    def GetAtomRadiusMethod(self):
        return _maptitude.RsccOptions_GetAtomRadiusMethod(self)

    def SetFixedAtomRadius(self, radius):
        return _maptitude.RsccOptions_SetFixedAtomRadius(self, radius)

    def GetFixedAtomRadius(self):
        return _maptitude.RsccOptions_GetFixedAtomRadius(self)

    def SetAtomRadiusScaling(self, scaling):
        return _maptitude.RsccOptions_SetAtomRadiusScaling(self, scaling)

    def GetAtomRadiusScaling(self):
        return _maptitude.RsccOptions_GetAtomRadiusScaling(self)

    atom_radius_method = property(GetAtomRadiusMethod, SetAtomRadiusMethod)
    fixed_atom_radius = property(GetFixedAtomRadius, SetFixedAtomRadius)
    atom_radius_scaling = property(GetAtomRadiusScaling, SetAtomRadiusScaling)


    def __init__(self):
        _maptitude.RsccOptions_swiginit(self, _maptitude.new_RsccOptions())
    __swig_destroy__ = _maptitude.delete_RsccOptions

# Register RsccOptions in _maptitude:
_maptitude.RsccOptions_swigregister(RsccOptions)
class RsrOptions(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def SetAtomRadiusMethod(self, method):
        return _maptitude.RsrOptions_SetAtomRadiusMethod(self, method)

    def GetAtomRadiusMethod(self):
        return _maptitude.RsrOptions_GetAtomRadiusMethod(self)

    def SetFixedAtomRadius(self, radius):
        return _maptitude.RsrOptions_SetFixedAtomRadius(self, radius)

    def GetFixedAtomRadius(self):
        return _maptitude.RsrOptions_GetFixedAtomRadius(self)

    def SetAtomRadiusScaling(self, scaling):
        return _maptitude.RsrOptions_SetAtomRadiusScaling(self, scaling)

    def GetAtomRadiusScaling(self):
        return _maptitude.RsrOptions_GetAtomRadiusScaling(self)

    atom_radius_method = property(GetAtomRadiusMethod, SetAtomRadiusMethod)
    fixed_atom_radius = property(GetFixedAtomRadius, SetFixedAtomRadius)
    atom_radius_scaling = property(GetAtomRadiusScaling, SetAtomRadiusScaling)


    def __init__(self):
        _maptitude.RsrOptions_swiginit(self, _maptitude.new_RsrOptions())
    __swig_destroy__ = _maptitude.delete_RsrOptions

# Register RsrOptions in _maptitude:
_maptitude.RsrOptions_swigregister(RsrOptions)
class CoverageOptions(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def SetSigma(self, sigma):
        return _maptitude.CoverageOptions_SetSigma(self, sigma)

    def GetSigma(self):
        return _maptitude.CoverageOptions_GetSigma(self)

    sigma = property(GetSigma, SetSigma)


    def __init__(self):
        _maptitude.CoverageOptions_swiginit(self, _maptitude.new_CoverageOptions())
    __swig_destroy__ = _maptitude.delete_CoverageOptions

# Register CoverageOptions in _maptitude:
_maptitude.CoverageOptions_swigregister(CoverageOptions)
class DensityScoreResult(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    overall = property(_maptitude.DensityScoreResult_overall_get, _maptitude.DensityScoreResult_overall_set)
    by_residue = property(_maptitude.DensityScoreResult_by_residue_get, _maptitude.DensityScoreResult_by_residue_set)
    by_atom = property(_maptitude.DensityScoreResult_by_atom_get, _maptitude.DensityScoreResult_by_atom_set)

    def ToString(self):
        return _maptitude.DensityScoreResult_ToString(self)

    def __repr__(self):
        return self.ToString()


    def __init__(self):
        _maptitude.DensityScoreResult_swiginit(self, _maptitude.new_DensityScoreResult())
    __swig_destroy__ = _maptitude.delete_DensityScoreResult

# Register DensityScoreResult in _maptitude:
_maptitude.DensityScoreResult_swigregister(DensityScoreResult)
class GridParams(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    x_origin = property(_maptitude.GridParams_x_origin_get, _maptitude.GridParams_x_origin_set)
    y_origin = property(_maptitude.GridParams_y_origin_get, _maptitude.GridParams_y_origin_set)
    z_origin = property(_maptitude.GridParams_z_origin_get, _maptitude.GridParams_z_origin_set)
    x_dim = property(_maptitude.GridParams_x_dim_get, _maptitude.GridParams_x_dim_set)
    y_dim = property(_maptitude.GridParams_y_dim_get, _maptitude.GridParams_y_dim_set)
    z_dim = property(_maptitude.GridParams_z_dim_get, _maptitude.GridParams_z_dim_set)
    x_spacing = property(_maptitude.GridParams_x_spacing_get, _maptitude.GridParams_x_spacing_set)
    y_spacing = property(_maptitude.GridParams_y_spacing_get, _maptitude.GridParams_y_spacing_set)
    z_spacing = property(_maptitude.GridParams_z_spacing_get, _maptitude.GridParams_z_spacing_set)

    def __init__(self):
        _maptitude.GridParams_swiginit(self, _maptitude.new_GridParams())
    __swig_destroy__ = _maptitude.delete_GridParams

# Register GridParams in _maptitude:
_maptitude.GridParams_swigregister(GridParams)
class UnitCellParams(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    a = property(_maptitude.UnitCellParams_a_get, _maptitude.UnitCellParams_a_set)
    b = property(_maptitude.UnitCellParams_b_get, _maptitude.UnitCellParams_b_set)
    c = property(_maptitude.UnitCellParams_c_get, _maptitude.UnitCellParams_c_set)
    alpha = property(_maptitude.UnitCellParams_alpha_get, _maptitude.UnitCellParams_alpha_set)
    beta = property(_maptitude.UnitCellParams_beta_get, _maptitude.UnitCellParams_beta_set)
    gamma = property(_maptitude.UnitCellParams_gamma_get, _maptitude.UnitCellParams_gamma_set)

    def __init__(self):
        _maptitude.UnitCellParams_swiginit(self, _maptitude.new_UnitCellParams())
    __swig_destroy__ = _maptitude.delete_UnitCellParams

# Register UnitCellParams in _maptitude:
_maptitude.UnitCellParams_swigregister(UnitCellParams)

def get_grid_params(grid):
    return _maptitude.get_grid_params(grid)

def get_unit_cell(grid):
    return _maptitude.get_unit_cell(grid)

def grid_contains(gp, x, y, z):
    return _maptitude.grid_contains(gp, x, y, z)

def same_grid_geometry(lhs, rhs, tol=1e-6):
    return _maptitude.same_grid_geometry(lhs, rhs, tol)

def interpolate_density(grid, x, y, z, default_value=0.0):
    return _maptitude.interpolate_density(grid, x, y, z, default_value)

def interpolate_density_batch(grid, points, num_points, default_value=0.0):
    return _maptitude.interpolate_density_batch(grid, points, num_points, default_value)

def get_atom_grid_points(grid, x, y, z, radius):
    return _maptitude.get_atom_grid_points(grid, x, y, z, radius)

def interpolate_density_periodic(grid, x, y, z, cell_a, cell_b, cell_c, default_value=0.0):
    r"""

    Trilinearly interpolate density, wrapping the query point into the unit cell.

    :param grid: Grid sampling one unit cell.
    :param x: Query x (Angstroms).
    :param y: Query y (Angstroms).
    :param z: Query z (Angstroms).
    :param cell_a: Unit cell dimension a (Angstroms).
    :param cell_b: Unit cell dimension b (Angstroms).
    :param cell_c: Unit cell dimension c (Angstroms).
    :param default_value: Returned where the grid cannot supply a value.
    :returns: Interpolated density at the wrapped point.
    :raises GridError: If an axis has fewer than two nodes, a node has no spatial
        coordinate or a non-finite one, or a derived interval is not finite and
        positive.
    :raises CellError: If the sampling is not axis-aligned, or if a cell edge does
        not round to ``n_i`` or ``n_i - 1`` of that axis's node intervals to within
        the allowance made for float node coordinates. Wrapping at a period the grid
        was never sampled on would resample the map onto a lattice it never had, so
        the caller is told rather than handed a plausible wrong number.

    """
    return _maptitude.interpolate_density_periodic(grid, x, y, z, cell_a, cell_b, cell_c, default_value)

def interpolate_density_periodic_batch(grid, points, num_points, cell_a, cell_b, cell_c, default_value=0.0):
    r"""

    Interpolate many points at once, wrapping each into the unit cell.

    :param grid: Grid sampling one unit cell.
    :param points: Flat sequence of x, y, z triples.
    :param num_points: Number of triples in ``points``.
    :param cell_a: Unit cell dimension a (Angstroms).
    :param cell_b: Unit cell dimension b (Angstroms).
    :param cell_c: Unit cell dimension c (Angstroms).
    :param default_value: Returned where the grid cannot supply a value.
    :returns: One interpolated density per point, in input order.
    :raises GridError: As :func:`interpolate_density_periodic`.
    :raises CellError: As :func:`interpolate_density_periodic`. The cell is checked
        once for the whole batch, before any point is sampled.

    """
    return _maptitude.interpolate_density_periodic_batch(grid, points, num_points, cell_a, cell_b, cell_c, default_value)
class CromerMannCoeffs(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    a = property(_maptitude.CromerMannCoeffs_a_get, _maptitude.CromerMannCoeffs_a_set)
    b = property(_maptitude.CromerMannCoeffs_b_get, _maptitude.CromerMannCoeffs_b_set)
    c = property(_maptitude.CromerMannCoeffs_c_get, _maptitude.CromerMannCoeffs_c_set)

    def Evaluate(self, s_squared):
        return _maptitude.CromerMannCoeffs_Evaluate(self, s_squared)

    def __init__(self):
        _maptitude.CromerMannCoeffs_swiginit(self, _maptitude.new_CromerMannCoeffs())
    __swig_destroy__ = _maptitude.delete_CromerMannCoeffs

# Register CromerMannCoeffs in _maptitude:
_maptitude.CromerMannCoeffs_swigregister(CromerMannCoeffs)
class ScatteringFactorEntry(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    atomic_number = property(_maptitude.ScatteringFactorEntry_atomic_number_get, _maptitude.ScatteringFactorEntry_atomic_number_set)
    formal_charge = property(_maptitude.ScatteringFactorEntry_formal_charge_get, _maptitude.ScatteringFactorEntry_formal_charge_set)
    coeffs = property(_maptitude.ScatteringFactorEntry_coeffs_get, _maptitude.ScatteringFactorEntry_coeffs_set)

    def __init__(self):
        _maptitude.ScatteringFactorEntry_swiginit(self, _maptitude.new_ScatteringFactorEntry())
    __swig_destroy__ = _maptitude.delete_ScatteringFactorEntry

# Register ScatteringFactorEntry in _maptitude:
_maptitude.ScatteringFactorEntry_swigregister(ScatteringFactorEntry)

def get_scattering_factors(atomic_number, formal_charge=0):
    return _maptitude.get_scattering_factors(atomic_number, formal_charge)
class DensityCalculator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, cell, symops):
        _maptitude.DensityCalculator_swiginit(self, _maptitude.new_DensityCalculator(cell, symops))
    __swig_destroy__ = _maptitude.delete_DensityCalculator

    def Calculate(self, mol, obs_grid, resolution, mask=None, k_sol=0.35, b_sol=46.0, include_h=False, n_scale_shells=1):
        return _maptitude.DensityCalculator_Calculate(self, mol, obs_grid, resolution, mask, k_sol, b_sol, include_h, n_scale_shells)

# Register DensityCalculator in _maptitude:
_maptitude.DensityCalculator_swigregister(DensityCalculator)

def rscc(*args):
    return _maptitude.rscc(*args)

def rsr(*args):
    return _maptitude.rsr(*args)

def qscore(*args):
    return _maptitude.qscore(*args)

def ediam(mol, grid, resolution, mask=None):
    return _maptitude.ediam(mol, grid, resolution, mask)

def coverage(*args):
    return _maptitude.coverage(*args)

def scale_map(grid, factor):
    return _maptitude.scale_map(grid, factor)

def combine_maps(lhs, rhs, op):
    return _maptitude.combine_maps(lhs, rhs, op)

def diff_to_calc(obs_grid, diff_grid):
    return _maptitude.diff_to_calc(obs_grid, diff_grid)

def wrap_and_pad_grid(grid, mol, cell_a, cell_b, cell_c, padding=3.0):
    return _maptitude.wrap_and_pad_grid(grid, mol, cell_a, cell_b, cell_c, padding)

def read_map(path, tiebreak):
    return _maptitude.read_map(path, tiebreak)

def write_map(*args):
    return _maptitude.write_map(*args)

def _get_scattering_factor_table_vec():
    return _maptitude._get_scattering_factor_table_vec()
class ScatteringFactorEntryVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _maptitude.ScatteringFactorEntryVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __bool__(self):
        return _maptitude.ScatteringFactorEntryVector___bool__(self)

    def __len__(self):
        return _maptitude.ScatteringFactorEntryVector___len__(self)

    def __delitem__(self, *args):
        return _maptitude.ScatteringFactorEntryVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _maptitude.ScatteringFactorEntryVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _maptitude.ScatteringFactorEntryVector___setitem__(self, *args)

    def pop(self):
        return _maptitude.ScatteringFactorEntryVector_pop(self)

    def append(self, x):
        return _maptitude.ScatteringFactorEntryVector_append(self, x)

    def empty(self):
        return _maptitude.ScatteringFactorEntryVector_empty(self)

    def size(self):
        return _maptitude.ScatteringFactorEntryVector_size(self)

    def swap(self, v):
        return _maptitude.ScatteringFactorEntryVector_swap(self, v)

    def begin(self):
        return _maptitude.ScatteringFactorEntryVector_begin(self)

    def end(self):
        return _maptitude.ScatteringFactorEntryVector_end(self)

    def rbegin(self):
        return _maptitude.ScatteringFactorEntryVector_rbegin(self)

    def rend(self):
        return _maptitude.ScatteringFactorEntryVector_rend(self)

    def clear(self):
        return _maptitude.ScatteringFactorEntryVector_clear(self)

    def get_allocator(self):
        return _maptitude.ScatteringFactorEntryVector_get_allocator(self)

    def pop_back(self):
        return _maptitude.ScatteringFactorEntryVector_pop_back(self)

    def erase(self, *args):
        return _maptitude.ScatteringFactorEntryVector_erase(self, *args)

    def __init__(self, *args):
        _maptitude.ScatteringFactorEntryVector_swiginit(self, _maptitude.new_ScatteringFactorEntryVector(*args))

    def push_back(self, x):
        return _maptitude.ScatteringFactorEntryVector_push_back(self, x)

    def front(self):
        return _maptitude.ScatteringFactorEntryVector_front(self)

    def back(self):
        return _maptitude.ScatteringFactorEntryVector_back(self)

    def assign(self, n, x):
        return _maptitude.ScatteringFactorEntryVector_assign(self, n, x)

    def resize(self, *args):
        return _maptitude.ScatteringFactorEntryVector_resize(self, *args)

    def insert(self, *args):
        return _maptitude.ScatteringFactorEntryVector_insert(self, *args)

    def reserve(self, n):
        return _maptitude.ScatteringFactorEntryVector_reserve(self, n)

    def capacity(self):
        return _maptitude.ScatteringFactorEntryVector_capacity(self)
    __swig_destroy__ = _maptitude.delete_ScatteringFactorEntryVector

# Register ScatteringFactorEntryVector in _maptitude:
_maptitude.ScatteringFactorEntryVector_swigregister(ScatteringFactorEntryVector)

import os

# Save references to SWIG-generated C++ wrappers before overriding
_cpp_rscc = rscc
_cpp_rsr = rsr
_cpp_qscore = qscore
_cpp_ediam = ediam
_cpp_coverage = coverage
_cpp_scale_map = scale_map
_cpp_combine_maps = combine_maps
_cpp_diff_to_calc = diff_to_calc
_cpp_wrap_and_pad_grid = wrap_and_pad_grid
_cpp_read_map = read_map
_cpp_write_map = write_map


def _lookup_atom_radius(metric, radius_map, name):
    """Resolve an atom-radius method name to its AtomRadius value.

    A bare ``radius_map[name.lower()]`` raised ``KeyError('vdw')`` on a
    misspelling: outside the typed exception hierarchy the README presents as the
    complete set to handle, and carrying no list of what would have worked.

    :param metric: Name of the calling metric, for the message.
    :param radius_map: Lower-case method name to AtomRadius value.
    :param name: The string the caller supplied.
    :returns: The AtomRadius value.
    :raises ValueError: If ``name`` matches no entry in ``radius_map``.
    """
    try:
        return radius_map[name.lower()]
    except KeyError:
        raise ValueError(
            "%s does not support atom_radius=%r; accepted values are %s"
            % (metric, name, ", ".join(repr(k) for k in sorted(radius_map)))
        ) from None


def _copy_rscc_options(options):
    """Return a copy of an RsccOptions so callers' objects are never mutated.

    :param options: Source options.
    :returns: An independent copy carrying the same settings.
    :raises TypeError: If ``options`` is not an RsccOptions.
    """
    if not isinstance(options, RsccOptions):
        raise TypeError(
            "options must be an RsccOptions, not %s" % type(options).__name__
        )
    copied = RsccOptions()
    copied.SetAtomRadiusMethod(options.GetAtomRadiusMethod())
    copied.SetFixedAtomRadius(options.GetFixedAtomRadius())
    copied.SetAtomRadiusScaling(options.GetAtomRadiusScaling())
    return copied


def _copy_rsr_options(options):
    """Return a copy of an RsrOptions so callers' objects are never mutated.

    :param options: Source options.
    :returns: An independent copy carrying the same settings.
    :raises TypeError: If ``options`` is not an RsrOptions.
    """
    if not isinstance(options, RsrOptions):
        raise TypeError(
            "options must be an RsrOptions, not %s" % type(options).__name__
        )
    copied = RsrOptions()
    copied.SetAtomRadiusMethod(options.GetAtomRadiusMethod())
    copied.SetFixedAtomRadius(options.GetFixedAtomRadius())
    copied.SetAtomRadiusScaling(options.GetAtomRadiusScaling())
    return copied


def _copy_coverage_options(options):
    """Return a copy of a CoverageOptions so callers' objects are never mutated.

    :param options: Source options.
    :returns: An independent copy carrying the same settings.
    :raises TypeError: If ``options`` is not a CoverageOptions.
    """
    if not isinstance(options, CoverageOptions):
        raise TypeError(
            "options must be a CoverageOptions, not %s" % type(options).__name__
        )
    copied = CoverageOptions()
    copied.SetSigma(options.GetSigma())
    return copied


def fc_density(obj, obs_grid, resolution, cell, mask=None,
               k_sol=0.35, b_sol=46.0, symops=None,
               include_h=False, n_scale_shells=1):
    """Compute model electron density via Fourier synthesis.

    :param obj: Input molecule (OEMolBase or OEDesignUnit).
    :param obs_grid: Observed electron density grid (OESkewGrid).
    :param resolution: Resolution limit in Angstroms.
    :param cell: UnitCell parameters.
    :param mask: Optional atom predicate to restrict contributing atoms.
    :param k_sol: Bulk solvent scale factor (default: 0.35 e/A^3).
    :param b_sol: Bulk solvent B-factor (default: 46.0 A^2).
    :param symops: Symmetry operators, as a semicolon-separated string, an
        iterable of SymOp, an iterable of operator strings, or None for the
        identity alone.
    :param include_h: Include hydrogen atoms (default: False).
    :param n_scale_shells: Number of per-shell scaling bins, in ``[1, 1000]``
        (default: 1). The upper bound is ``MAX_SCALE_SHELLS``: the bins partition
        the resolution range and even a 0.5 A dataset has far fewer independent
        shells, while a value near ``UINT_MAX`` sizes the shell-edge table into
        tens of gigabytes and at ``UINT_MAX`` itself wraps it to zero.
    :returns: OESkewGrid with computed model density.
    :raises TypeError: If ``symops`` is neither a string nor an iterable of
        SymOp or operator strings.
    :raises SymOpError: If an operator string cannot be parsed.
    :raises GridError: If ``resolution`` is not finite and positive, if
        ``n_scale_shells`` is outside ``[1, 1000]``, if ``obs_grid``'s spacing is
        at or above twice a cell edge, or if the resolution and the cell together
        need a Miller-index box of more than 2e8 points.
    :raises CellError: If ``cell`` is invalid or is not orthorhombic.
    """
    if symops is None:
        symops = [SymOp()]  # Identity only
    elif isinstance(symops, str):
        symops = list(SymOp.ParseAll(symops))
    elif isinstance(symops, SymOp):
# A lone SymOp is not iterable, so it would reach the generic message below
# and be reported as "not SymOp" -- a type this function does accept, inside
# a sequence. Name the wrapping the caller has to do instead.
        raise TypeError(
            "symops must be a sequence of SymOp, not a single SymOp; pass [symops]"
        )
    elif isinstance(symops, (bytes, bytearray)):
# bytes and bytearray iterate as ints, so the per-element check below would
# report "not int" for input the caller never wrote as integers.
        raise TypeError(
            "symops must be a str, not %s; decode it first" % type(symops).__name__
        )
    else:
        try:
            elements = list(symops)
        except TypeError:
            raise TypeError(
                "symops must be a string, an iterable of SymOp, or an iterable of "
                "operator strings, not %s" % type(symops).__name__
            ) from None
# A list of operator strings is the shape this docstring describes, so
# accept it here rather than letting SymOpVector reject it with a raw SWIG
# overload dump. ParseAll is the same path the bare-string branch takes.
        normalized = []
        for element in elements:
            if isinstance(element, SymOp):
                normalized.append(element)
            elif isinstance(element, str):
                normalized.extend(SymOp.ParseAll(element))
            else:
                raise TypeError(
                    "symops entries must be SymOp or str, not %s"
                    % type(element).__name__
                )
        symops = normalized

    calc = DensityCalculator(cell, SymOpVector(symops))
    return calc.Calculate(obj, obs_grid, resolution, mask,
                          k_sol, b_sol, include_h, n_scale_shells)


def rscc(obj, grid, resolution, mask=None, calc_grid=None,
         atom_radius=None, options=None):
    """Real-Space Correlation Coefficient.

    :param obj: Input molecule.
    :param grid: Observed electron density map.
    :param resolution: Resolution in Angstroms.
    :param mask: Optional atom predicate.
    :param calc_grid: Optional pre-computed calculated density.
    :param atom_radius: Atom radius method, as an AtomRadius enum value or one of
        the strings ``"fixed"``, ``"scaled"``, ``"binned"`` (case-insensitive).
        ``"adaptive"`` is not accepted: rscc has no adaptive radius model.
    :param options: RsccOptions configuration object. Never mutated.
    :returns: DensityScoreResult with RSCC values.
    :raises ValueError: If ``atom_radius`` is a string naming no supported method,
        including ``"adaptive"``.
    :raises RuntimeError: If ``atom_radius`` is ``AtomRadius.ADAPTIVE``, or if
        ``options`` carries it. The two spellings of the same rejection raise
        different types because they are found in different places: the string is
        resolved against a table here, where "no such method" is a ValueError,
        while the enum value is a real method that this metric does not implement
        and is refused by the C++ layer, whose ``std::invalid_argument`` surfaces
        as RuntimeError like every other option-value rejection.
    """
    if options is None:
        options = RsccOptions()
    if atom_radius is not None:
        if isinstance(atom_radius, str):
# Three entries, not four: rscc has no adaptive radius model and the
# enum path rejects AtomRadius.ADAPTIVE, so omitting it here is the
# agreeing behavior rather than an oversight.
            _radius_map = {
                "fixed": AtomRadius_FIXED,
                "scaled": AtomRadius_SCALED,
                "binned": AtomRadius_BINNED,
            }
            atom_radius = _lookup_atom_radius("rscc", _radius_map, atom_radius)
# Copy: mutating the caller's options object would leak this call's
# settings into their next call.
        options = _copy_rscc_options(options)
        options.SetAtomRadiusMethod(atom_radius)
    return _cpp_rscc(obj, grid, resolution, mask, calc_grid, options)


def rsr(obj, grid, resolution, mask=None, calc_grid=None,
        atom_radius=None, options=None):
    """Real-Space R-Factor.

    :param obj: Input molecule.
    :param grid: Observed electron density map.
    :param resolution: Resolution in Angstroms.
    :param mask: Optional atom predicate.
    :param calc_grid: Optional pre-computed calculated density.
    :param atom_radius: Atom radius method, as an AtomRadius enum value or one of
        the strings ``"fixed"``, ``"scaled"``, ``"binned"``, ``"adaptive"``
        (case-insensitive).
    :param options: RsrOptions configuration object. Never mutated.
    :returns: DensityScoreResult with RSR values.
    :raises ValueError: If ``atom_radius`` is a string naming no supported method.
    """
    if options is None:
        options = RsrOptions()
    if atom_radius is not None:
        if isinstance(atom_radius, str):
            _radius_map = {
                "fixed": AtomRadius_FIXED,
                "scaled": AtomRadius_SCALED,
                "binned": AtomRadius_BINNED,
                "adaptive": AtomRadius_ADAPTIVE,
            }
            atom_radius = _lookup_atom_radius("rsr", _radius_map, atom_radius)
# Copy: mutating the caller's options object would leak this call's
# settings into their next call.
        options = _copy_rsr_options(options)
        options.SetAtomRadiusMethod(atom_radius)
    return _cpp_rsr(obj, grid, resolution, mask, calc_grid, options)


def qscore(obj, grid, resolution, mask=None, options=None):
    """Q-Score (Pintilie et al., 2020).

    :param obj: Input molecule.
    :param grid: Observed electron density map.
    :param resolution: Resolution in Angstroms.
    :param mask: Optional atom predicate.
    :param options: QScoreOptions configuration.
    :returns: DensityScoreResult with Q-score values.
    """
    if options is None:
        options = QScoreOptions()
    return _cpp_qscore(obj, grid, resolution, mask, options)


def ediam(obj, grid, resolution, mask=None):
    """Electron Density Index Averaged, Modified (EDIAm).

    :param obj: Input molecule.
    :param grid: Observed electron density map.
    :param resolution: Resolution in Angstroms.
    :param mask: Optional atom predicate.
    :returns: DensityScoreResult with EDIAm values in [0, 1].
    """
    return _cpp_ediam(obj, grid, resolution, mask)


def coverage(obj, grid, sigma=None, mask=None, options=None):
    """Coverage: fraction of atoms observed in density.

    :param obj: Input molecule.
    :param grid: Observed electron density map.
    :param sigma: Number of standard deviations above mean. When None, the
        value carried by ``options`` is used. An explicit value overrides it.
    :param mask: Optional atom predicate.
    :param options: CoverageOptions configuration object. Never mutated.
    :returns: DensityScoreResult with coverage fractions.
    """
    if options is None:
        options = CoverageOptions()
    if sigma is not None:
        options = _copy_coverage_options(options)
        options.SetSigma(sigma)
    return _cpp_coverage(obj, grid, mask, options)


def parse_symop(s):
    """Parse a single symmetry operator from triplet notation.

    :param s: Symmetry operator string (e.g., "x,y,z" or "-x,y+1/2,-z").
    :returns: SymOp object.
    """
    return SymOp.Parse(s)


def parse_symops(text):
    """Parse multiple symmetry operators from newline/semicolon-separated text.

    :param text: Block of symmetry operators.
    :returns: List of SymOp objects.
    """
    return list(SymOp.ParseAll(text))


def scale_map(grid, factor):
    """Scale a grid by multiplying all values by a scalar.

    :param grid: Grid to scale (modified in place).
    :param factor: Scale factor.
    """
    _cpp_scale_map(grid, factor)


def combine_maps(lhs, rhs, op):
    """Combine two grids element-wise.

    :param lhs: Left-hand side grid.
    :param rhs: Right-hand side grid.
    :param op: MapOp enum value (ADD, SUBTRACT, MIN, MAX).
    :returns: New OESkewGrid with combined values.
    :raises TypeError: When ``op`` is not a Python ``int``, or is a ``bool``.
        ``bool`` subclasses ``int``, but neither ``True`` nor ``False`` names an
        operation, so both are rejected. A NumPy integer scalar is rejected here
        too, since the check is on the Python type.
    :raises ValueError: When ``op`` is an ``int`` outside 0-3 that fits in a C
        ``long``. One too large to fit raises ``OverflowError`` instead.
    """
    return _cpp_combine_maps(lhs, rhs, op)


def diff_to_calc(obs_grid, diff_grid):
    """Derive calculated density from observed and difference maps.

    :param obs_grid: Observed density map (2mFo-DFc).
    :param diff_grid: Difference density map (mFo-DFc).
    :returns: New OESkewGrid with calculated density.
    """
    return _cpp_diff_to_calc(obs_grid, diff_grid)


class MapFile(tuple):
    """The contents of a map file: its density grid and its symmetry text.

    A 2-tuple of ``(grid, symops)`` with the two members also reachable by
    name, so ``result.grid`` and ``grid, symops = read_map(path)`` both work.
    """

    __slots__ = ()

    def __new__(cls, grid, symops):
        return tuple.__new__(cls, (grid, symops))

    @property
    def grid(self):
        """The density carrier, an ``OESkewGrid`` at the file's origin."""
        return self[0]

    @property
    def symops(self):
        """Newline-separated triplets; ``""`` when the file carries none."""
        return self[1]

    def __repr__(self):
        return "MapFile(grid={0!r}, symops={1!r})".format(self[0], self[1])


def read_map(path, tiebreak=OriginSource_ORIGIN_RECORD):
    """Read a CCP4 or MRC map, preserving its ORIGIN record and symmetry block.

    OEReadGrid returns the payload, the cell and the space group but never
    consults the MRC2000 ORIGIN record and does not expose the symmetry block.
    This reads both and returns a grid already moved onto the file's origin.

    :param path: Map file to read. A ``str`` or any :class:`os.PathLike`.
    :param tiebreak: Which record wins when ORIGIN and NxSTART both encode a
        nonzero origin, whether or not the two agree -- nothing here compares
        them. One of ``OriginSource.ORIGIN_RECORD`` (the default) or
        ``OriginSource.NXSTART``. Ignored when at most one is nonzero.
    :returns: A :class:`MapFile` of ``(grid, symops)``.
    :raises TypeError: If ``path`` is neither a ``str`` nor an
        :class:`os.PathLike`. A ``bytes`` path is also rejected, by the
        ``std::string`` typemap rather than by ``os.fspath``. Also when
        ``tiebreak`` is not a Python ``int``, or is a ``bool``. ``bool``
        subclasses ``int``, but neither ``True`` nor ``False`` names a tiebreak
        rule, so both are rejected. A NumPy integer scalar is rejected here
        too, since the check is on the Python type.
    :raises CellError: If the file's sampling is not axis-aligned. maptitude
        requires an orthorhombic cell; a skewed one is rejected on read.
    :raises GridError: If the file cannot be read, its header cannot be
        parsed, or the copy that returns the grid to Python did not preserve
        the source geometry -- a degenerate cell edge reaches this. Also if
        ``path`` contains an embedded NUL, which ``os.fspath`` passes through
        unchanged: the calls that open the file stop at the NUL, so the name
        given and the name opened are not the same name.
    :raises SymOpError: If the symmetry block is present and does not parse.
    :raises ValueError: When ``tiebreak`` is an ``int`` outside 0-1 that fits
        in a C ``long``. One too large to fit raises ``OverflowError``.

    Example::

        result = read_map("2fofc.ccp4")
        symops = parse_symops(result.symops) if result.symops else None
    """
    grid, symops = _cpp_read_map(os.fspath(path), tiebreak)
    return MapFile(grid, symops)


def write_map(path, grid, symops=""):
    """Write a grid as CCP4 or MRC, restoring the ORIGIN and symmetry records.

    The file is written and verified under a temporary name and renamed onto
    ``path`` only once it reads back as the grid it came from, so a grid that
    cannot be written faithfully raises with ``path`` untouched rather than
    leaving a wrong map on disk or destroying a good one.

    A successful write replaces the destination's inode rather than rewriting
    it in place, so three properties of an existing destination do not survive.
    Its mode resets to whatever an ordinary create gives, which under POSIX is
    0666 narrowed by the process umask, widening a permission the caller had
    narrowed. Hard links to it keep the old contents under their own names. A
    destination that was a symlink becomes a regular file, with its former
    target left untouched.

    The verification covers the bytes this function wrote, not the bytes that
    arrive at ``path``. It writes and checks a temporary beside the destination
    and then renames that onto ``path``, and every step addresses the temporary
    by path. So a process able to write the destination's directory can replace
    the temporary between the last check and the rename, and this function will
    publish its bytes and return successfully. Such a process can already
    create, replace and remove ``path`` itself; what this adds is that a
    successful return stops implying the published bytes are the ones that were
    verified. A destination directory only the caller can write closes that.

    Node 0 is written twice, into the MRC2000 ORIGIN record exactly and into
    NxSTART as an integer node count. A map this function wrote reproduces node
    0 to float32 under ``OriginSource.ORIGIN_RECORD`` and only to half a node
    interval per axis under ``OriginSource.NXSTART``, and the write is refused
    unless the two records agree on every axis to within that bound.

    That bound is per axis, and there is no second one over the three together:
    each axis is compared against its own node interval. So the straight-line
    distance between the two placements can reach the root-sum-square of the
    three half-intervals -- ``sqrt(3)`` times half a node interval on a grid
    sampled equally on all three axes -- and a caller budgeting one distance
    rather than three per-axis bounds needs that larger figure.

    The padded grid :func:`wrap_and_pad_grid` allocates when padding is needed
    is refused: its declared cell forces the written node count one higher per
    axis than the grid carries. That is a property of the newly allocated grid,
    not of every value that function returns: when no padding is needed it
    hands back the grid it was given.

    :param path: Destination. The format follows the extension; the admitted
        class is every spelling whose first three characters are ``ccp``,
        ``map`` or ``mrc``, compared case-insensitively. ``.ccp4``, ``.mrc``
        and ``.map`` are the spellings this writer is tested on, not the
        accepted set. A compressed destination such as ``.ccp4.gz`` is refused,
        as is a filename that is nothing but an extension. A ``str`` or any
        :class:`os.PathLike`.
    :param grid: Grid to write, an ``OESkewGrid``.
    :param symops: Symmetry text in the form :func:`read_map` returns, one
        triplet per line. Empty writes no symmetry block. The semicolon
        separator is normalized to a newline, so the operator set survives
        a round trip but that spelling does not.
    :raises TypeError: If ``path`` is neither a ``str`` nor an :class:`os.PathLike`.
        A ``bytes`` path is also rejected, by the ``std::string`` typemap rather than
        by ``os.fspath``.
    :raises CellError: If the grid's sampling is not axis-aligned. maptitude
        requires an orthorhombic cell; a skewed one is rejected on write.
    :raises GridError: If the extension is not one OpenEye maps to the CCP4
        format or names a compressed file, if the temporary this function
        writes beside ``path`` cannot be created, which an unwritable or absent
        destination directory produces, if eight attempts at a temporary name
        beside ``path`` all collide with an existing file, if the write fails,
        if the re-read map differs from the grid in dimensions, cell, per-axis
        spacing, node 0 or any voxel, if either the grid or the re-read map has
        an axis with fewer than two nodes, so its spacing is undefined, if on
        any axis the ORIGIN and NxSTART records place node 0 more than half
        that axis's node interval apart, or if the verified temporary file
        cannot be renamed onto ``path``. Also if ``path`` contains an embedded
        NUL, which ``os.fspath`` passes through unchanged: the extension gate
        reads the whole string while the calls that write and publish the file
        stop at the NUL, so the name checked and the name written are not the
        same name. That list is what a caller can predict from ``path``,
        ``grid`` and the state of the destination. Steps this function drives
        internally raise ``GridError`` too when they do not produce a usable
        file, so catch the class rather than switching on the list.
    :raises SymOpError: If ``symops`` is non-empty and does not parse, or if
        any of its records is longer than the format's 80-character field.
    """
    _cpp_write_map(os.fspath(path), grid, symops)


def wrap_and_pad_grid(grid, mol, cell_a, cell_b, cell_c, padding=3.0):
    """Translate molecule into unit cell and pad grid if needed.

    :param grid: CCP4 unit-cell grid.
    :param mol: Molecule to wrap (modified in-place).
    :param cell_a: Unit cell dimension a (Angstroms). Must be finite and positive.
    :param cell_b: Unit cell dimension b (Angstroms). Must be finite and positive.
    :param cell_c: Unit cell dimension c (Angstroms). Must be finite and positive.
    :param padding: Extra margin around atoms (Angstroms).
    :returns: A padded grid, or the original grid when no padding is needed.
        Never ``None``: the C++ function returns a null grid to mean "no padding
        was needed", and this wrapper substitutes the original.
    :raises StructureError: If the molecule contains no heavy atoms.
    :raises CellError: If any cell edge is zero, negative, or non-finite. The
        wrap uses ``fmod`` against each edge, which is NaN for a zero divisor and
        previously filled the padded grid with NaN voxels. Also if an edge does
        not round to ``n_i`` or ``n_i - 1`` of that axis's node intervals, to
        within the allowance made for float node coordinates: the padded grid is
        filled by sampling this one periodically, which needs the grid to tile
        the cell it is given.
    """
    result = _cpp_wrap_and_pad_grid(grid, mol, cell_a, cell_b, cell_c, padding)
    return result if result is not None else grid


def get_scattering_factor_table():
    """Get the full scattering factor table.

    :returns: Tuple of (table_entries, count).
    """
    entries = _get_scattering_factor_table_vec()
    return entries, len(entries)


__version__ = "0.5.0"


